<?php

declare(strict_types=1);

namespace App\Modules\Core\Authorization\Application\Roles;

use App\Modules\Core\Authorization\Application\Permissions\CoreAuthorizationPermissionCatalog;
use App\Shared\Application\Calendar\Permissions\CalendarPermissionNames;
use App\Shared\Application\Chat\Permissions\ChatPermissionNames;
use App\Shared\Application\Notifications\Permissions\NotificationPermissionNames;
use App\Shared\Application\Teams\Permissions\TeamPermissionNames;
use App\Shared\Application\Users\Permissions\UserPermissionNames;

final class StarterRoleCatalog
{
    /**
     * @param  list<string>  $allPermissionNames
     * @return list<StarterRoleDefinition>
     */
    public function definitions(array $allPermissionNames): array
    {
        return [
            new StarterRoleDefinition(StarterRoleName::WorkspaceAccess, [
                CoreAuthorizationPermissionCatalog::DASHBOARD,
                UserPermissionNames::USERS_PROFILE,
                UserPermissionNames::USERS_PROFILE_AVATAR_IMAGE,
                UserPermissionNames::USERS_PROFILE_AVATAR_UPDATE,
                UserPermissionNames::USERS_PROFILE_PASSWORD_UPDATE,
                UserPermissionNames::USERS_PROFILE_NOTIFICATION_EMAILS_STORE,
                UserPermissionNames::USERS_PROFILE_NOTIFICATION_EMAILS_UPDATE,
                'team.switch',
                NotificationPermissionNames::NOTIFICATIONS_INDEX,
                NotificationPermissionNames::NOTIFICATIONS_READ,
                NotificationPermissionNames::NOTIFICATIONS_READ_BULK,
                NotificationPermissionNames::REALTIME_EVENTS,
                CalendarPermissionNames::INDEX,
                CalendarPermissionNames::EVENT_STORE,
                CalendarPermissionNames::EVENT_UPDATE,
                CalendarPermissionNames::EVENT_DESTROY,
                CalendarPermissionNames::PREFERENCE_UPDATE,
                ChatPermissionNames::INDEX,
                ChatPermissionNames::DIRECT_CONVERSATION_STORE,
                ChatPermissionNames::GROUP_STORE,
                ChatPermissionNames::TEAM_CONVERSATION_SHOW,
                ChatPermissionNames::MESSAGE_STORE,
                ChatPermissionNames::CONTENT_INDEX,
                ChatPermissionNames::ATTACHMENT_STORE,
                ChatPermissionNames::ATTACHMENT_SHOW,
                ChatPermissionNames::ATTACHMENT_RETRY,
                ChatPermissionNames::ATTACHMENT_DESTROY,
                ChatPermissionNames::ATTACHMENT_DOWNLOAD,
                ChatPermissionNames::VOICE_MESSAGE_STORE,
                ChatPermissionNames::CALL_START,
                ChatPermissionNames::CALL_JOIN,
                ChatPermissionNames::SCREEN_SHARE_STORE,
                ChatPermissionNames::MEETING_STORE,
                ChatPermissionNames::MEETING_INVITATION_STORE,
                ChatPermissionNames::RECORDING_SHOW,
                ChatPermissionNames::RECORDING_DOWNLOAD,
                ChatPermissionNames::TRANSCRIPTION_STORE,
                ChatPermissionNames::TRANSCRIPTION_SHOW,
            ]),
            new StarterRoleDefinition(StarterRoleName::CommunicationAccess, [
                CalendarPermissionNames::INDEX,
                CalendarPermissionNames::EVENT_STORE,
                CalendarPermissionNames::EVENT_UPDATE,
                CalendarPermissionNames::EVENT_DESTROY,
                CalendarPermissionNames::PREFERENCE_UPDATE,
                ChatPermissionNames::INDEX,
                ChatPermissionNames::DIRECT_CONVERSATION_STORE,
                ChatPermissionNames::GROUP_STORE,
                ChatPermissionNames::TEAM_CONVERSATION_SHOW,
                ChatPermissionNames::MESSAGE_STORE,
                ChatPermissionNames::CONTENT_INDEX,
                ChatPermissionNames::ATTACHMENT_STORE,
                ChatPermissionNames::ATTACHMENT_SHOW,
                ChatPermissionNames::ATTACHMENT_RETRY,
                ChatPermissionNames::ATTACHMENT_DESTROY,
                ChatPermissionNames::ATTACHMENT_DOWNLOAD,
                ChatPermissionNames::VOICE_MESSAGE_STORE,
                ChatPermissionNames::CALL_START,
                ChatPermissionNames::CALL_JOIN,
                ChatPermissionNames::SCREEN_SHARE_STORE,
                ChatPermissionNames::MEETING_STORE,
                ChatPermissionNames::MEETING_INVITATION_STORE,
                ChatPermissionNames::RECORDING_SHOW,
                ChatPermissionNames::RECORDING_DOWNLOAD,
                ChatPermissionNames::TRANSCRIPTION_STORE,
                ChatPermissionNames::TRANSCRIPTION_SHOW,
            ]),
            new StarterRoleDefinition(StarterRoleName::CommunicationMeetingHost, [
                ChatPermissionNames::INDEX,
                ChatPermissionNames::CALL_START,
                ChatPermissionNames::CALL_JOIN,
                ChatPermissionNames::SCREEN_SHARE_STORE,
                ChatPermissionNames::MEETING_STORE,
                ChatPermissionNames::MEETING_INVITATION_STORE,
                ChatPermissionNames::MEETING_MODERATE,
                ChatPermissionNames::RECORDING_MANAGE,
                ChatPermissionNames::RECORDING_SHOW,
                ChatPermissionNames::RECORDING_DOWNLOAD,
                ChatPermissionNames::RECORDING_SHARE,
                ChatPermissionNames::TRANSCRIPTION_STORE,
                ChatPermissionNames::TRANSCRIPTION_SHOW,
                ChatPermissionNames::TRANSCRIPTION_UPDATE,
                ChatPermissionNames::TRANSCRIPTION_SHARE,
            ]),
            new StarterRoleDefinition(StarterRoleName::CommunicationOperations, [
                ChatPermissionNames::INDEX,
                ChatPermissionNames::ADMIN_OPERATIONS_INDEX,
                ChatPermissionNames::ADMIN_RETENTION_UPDATE,
                ChatPermissionNames::ADMIN_RECORDING_RETENTION_UPDATE,
            ]),
            new StarterRoleDefinition(StarterRoleName::AdminUsersRead, [
                'admin.users.index',
            ]),
            new StarterRoleDefinition(StarterRoleName::AdminUsersManage, [
                'admin.users.index',
                'admin.users.create',
                'admin.users.store',
                'admin.users.edit',
                'admin.users.update',
                'admin.users.activate',
                'admin.users.deactivate',
                'admin.users.verify-email',
                'admin.users.require-email-verification',
                'admin.users.resend-first-password',
                'admin.users.unlock',
                'admin.users.reset-mfa',
                'admin.users.invalidate-sessions',
                CoreAuthorizationPermissionCatalog::ADMIN_USERS_IMPERSONATE,
                CoreAuthorizationPermissionCatalog::ADMIN_USERS_IMPERSONATE_STORE,
                CoreAuthorizationPermissionCatalog::IMPERSONATION_START,
                'admin.users.teams.store',
                'admin.users.teams.destroy',
                'admin.users.teams.authorization.update',
            ]),
            new StarterRoleDefinition(StarterRoleName::AdminTeamsRead, [
                'admin.teams.index',
            ]),
            new StarterRoleDefinition(StarterRoleName::AdminTeamsManage, [
                'admin.teams.index',
                'admin.teams.create',
                'admin.teams.store',
                'admin.teams.edit',
                'admin.teams.update',
                'admin.teams.activate',
                'admin.teams.deactivate',
                'admin.teams.destroy',
                'admin.teams.users.store',
                'admin.teams.users.destroy',
                'admin.teams.users.authorization.update',
            ]),
            new StarterRoleDefinition(StarterRoleName::AuthorizationRolesRead, [
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_ROLES,
                CoreAuthorizationPermissionCatalog::ROLES_VIEW,
            ]),
            new StarterRoleDefinition(StarterRoleName::AuthorizationRolesManage, [
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_ROLES,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_ROLES_CREATE,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_ROLES_STORE,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_ROLES_EDIT,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_ROLES_UPDATE,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_ROLES_DELETE,
                CoreAuthorizationPermissionCatalog::ROLES_VIEW,
                CoreAuthorizationPermissionCatalog::ROLES_CREATE,
                CoreAuthorizationPermissionCatalog::ROLES_UPDATE,
                CoreAuthorizationPermissionCatalog::ROLES_DELETE,
            ]),
            new StarterRoleDefinition(StarterRoleName::AuthorizationPresetsManage, [
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_PACKAGES,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_PACKAGES_CREATE,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_PACKAGES_STORE,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_PACKAGES_EDIT,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_PACKAGES_UPDATE,
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_PACKAGES_DELETE,
            ]),
            new StarterRoleDefinition(StarterRoleName::AuthorizationPermissionsRead, [
                CoreAuthorizationPermissionCatalog::ADMIN_AUTHORIZATION_PERMISSIONS,
                CoreAuthorizationPermissionCatalog::PERMISSIONS_VIEW,
            ]),
            new StarterRoleDefinition(StarterRoleName::TeamManagersRead, [
                'admin.teams.structure.show',
                TeamPermissionNames::MANAGERS_VIEW,
                TeamPermissionNames::MANAGERS_TREE,
                TeamPermissionNames::MANAGERS_HISTORY,
            ]),
            new StarterRoleDefinition(StarterRoleName::TeamManagersManage, [
                'admin.teams.structure.show',
                'admin.teams.structure.relationships.store',
                'admin.teams.structure.relationships.end',
                'admin.teams.structure.structural-role.update',
                TeamPermissionNames::MANAGERS_VIEW,
                TeamPermissionNames::MANAGERS_CREATE,
                TeamPermissionNames::MANAGERS_UPDATE,
                TeamPermissionNames::MANAGERS_TERMINATE,
                TeamPermissionNames::MANAGERS_TREE,
                TeamPermissionNames::MANAGERS_HISTORY,
                TeamPermissionNames::MANAGERS_HEAD_UPDATE,
            ]),
            new StarterRoleDefinition(StarterRoleName::SystemStatusRead, [
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_RELEASE,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_READINESS,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_MODULES,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_SCHEDULER,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_MODULE_ACTIVATION,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_FAILED_JOBS,
                CoreAuthorizationPermissionCatalog::SYSTEM_STATUS_VIEW,
                CoreAuthorizationPermissionCatalog::QUEUES_VIEW,
                CoreAuthorizationPermissionCatalog::ADMIN_QUEUES_INDEX,
                CoreAuthorizationPermissionCatalog::ADMIN_PULSE_VIEW,
                CoreAuthorizationPermissionCatalog::ADMIN_TELESCOPE_VIEW,
            ]),
            new StarterRoleDefinition(StarterRoleName::SystemOperationsManage, [
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_RELEASE,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_READINESS,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_MODULES,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_SCHEDULER,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_MODULE_ACTIVATION,
                CoreAuthorizationPermissionCatalog::ADMIN_SYSTEM_STATUS_FAILED_JOBS,
                CoreAuthorizationPermissionCatalog::SYSTEM_STATUS_VIEW,
                CoreAuthorizationPermissionCatalog::QUEUES_VIEW,
                CoreAuthorizationPermissionCatalog::QUEUES_MANAGE,
                CoreAuthorizationPermissionCatalog::ADMIN_QUEUES_INDEX,
                CoreAuthorizationPermissionCatalog::ADMIN_QUEUES_RETRY,
                CoreAuthorizationPermissionCatalog::ADMIN_QUEUES_ACKNOWLEDGE,
                CoreAuthorizationPermissionCatalog::ADMIN_PULSE_VIEW,
                CoreAuthorizationPermissionCatalog::ADMIN_TELESCOPE_VIEW,
                CoreAuthorizationPermissionCatalog::ADMIN_RATE_LIMITS_INDEX,
                CoreAuthorizationPermissionCatalog::ADMIN_RATE_LIMITS_RESET,
                CoreAuthorizationPermissionCatalog::ADMIN_LOGS_INDEX,
                CoreAuthorizationPermissionCatalog::MODULE_ACTIVATION_VIEW,
                CoreAuthorizationPermissionCatalog::MODULE_ACTIVATION_UPDATE,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_INDEX,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_SHOW,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_TEAMS_CREATE,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_GLOBAL_UPDATE,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_TEAM_UPDATE,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_TEAM_CLEAR,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_GLOBAL_SCHEDULE,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_TEAM_SCHEDULE,
                CoreAuthorizationPermissionCatalog::ADMIN_MODULES_SCHEDULE_CANCEL,
            ]),
            new StarterRoleDefinition(StarterRoleName::Administrator, $allPermissionNames),
        ];
    }
}
