port: 7880
redis:
  address: redis:6379
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50020
  use_external_ip: false
  node_ip: 127.0.0.1
room:
  auto_create: false
  empty_timeout: 900
  departure_timeout: 900
  max_participants: 0
logging:
  level: info
  json: false
