<?php

declare(strict_types=1);

use App\Modules\Core\Audit\Presentation\Http\Controllers\AuditBrowserController;
use App\Modules\Core\Audit\Presentation\Http\Controllers\SecurityHistoryController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\CreateOnboardingPackageController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\CreateRoleController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\DestroyOnboardingPackageController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\DestroyRoleController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\EditOnboardingPackageController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\EditRoleController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\OnboardingPackageAdministrationController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\PermissionAdministrationController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\RoleAdministrationController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\StoreOnboardingPackageController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\StoreRoleController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\UpdateOnboardingPackageController;
use App\Modules\Core\Authorization\Presentation\Http\Controllers\UpdateRoleController;
use App\Modules\Core\Files\Presentation\Http\Controllers\AdminFilesController;
use App\Modules\Core\Identity\Application\Admin\HighRiskAdministrativeOperation;
use App\Modules\Core\Identity\Presentation\Http\Controllers\AdminModeController;
use App\Modules\Core\Identity\Presentation\Http\Controllers\ImpersonationController;
use App\Modules\Core\Identity\Presentation\Http\Controllers\RateLimitAdministrationController;
use App\Modules\Core\Identity\Presentation\Http\Controllers\ResetRateLimitCounterController;
use App\Modules\Core\Teams\Presentation\Http\Controllers\ManagerHierarchyAdministrationController;
use App\Modules\Core\Teams\Presentation\Http\Controllers\TeamAdministrationController;
use App\Modules\Core\Teams\Presentation\Http\Controllers\UserTeamAuthorizationController;
use App\Modules\Core\Teams\Presentation\Http\Controllers\UserTeamMembershipController;
use App\Modules\Core\Users\Presentation\Http\Controllers\CreateUserAccountController;
use App\Modules\Core\Users\Presentation\Http\Controllers\EditUserAccountController;
use App\Modules\Core\Users\Presentation\Http\Controllers\StoreUserAccountController;
use App\Modules\Core\Users\Presentation\Http\Controllers\UpdateUserAccountController;
use App\Modules\Core\Users\Presentation\Http\Controllers\UserAccountActionController;
use App\Modules\Core\Users\Presentation\Http\Controllers\UserAdministrationController;
use App\Modules\Optional\Integrations\Presentation\Http\Controllers\AdminIntegrationsController;
use App\Shared\Presentation\Http\Controllers\AdminApplicationLogController;
use App\Shared\Presentation\Http\Controllers\AdminFailedJobController;
use App\Shared\Presentation\Http\Controllers\AdminSystemStatusController;
use App\Shared\Presentation\Http\Controllers\Modules\ModuleActivationController;
use App\Shared\Presentation\Http\Controllers\TableSavedViewController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'route.permission'])->group(function (): void {
    Route::get('/admin-mode', [AdminModeController::class, 'enter'])->name('admin-mode.enter');
    Route::get('/admin-mode/high-risk', [AdminModeController::class, 'highRisk'])->name('admin-mode.high-risk');
    Route::delete('/admin-mode', [AdminModeController::class, 'exit'])->name('admin-mode.exit');
    Route::delete('/impersonation', [ImpersonationController::class, 'destroy'])->name('impersonation.destroy');
});

Route::middleware(['auth', 'admin.mode', 'route.permission'])->group(function (): void {
    Route::get('/admin', AdminSystemStatusController::class)->name('admin.system-status');
    Route::get('/admin/system-status/release', [AdminSystemStatusController::class, 'release'])->name('admin.system-status.release');
    Route::get('/admin/system-status/readiness', [AdminSystemStatusController::class, 'readiness'])->name('admin.system-status.readiness');
    Route::get('/admin/system-status/modules', [AdminSystemStatusController::class, 'modules'])->name('admin.system-status.modules');
    Route::get('/admin/system-status/scheduler', [AdminSystemStatusController::class, 'scheduler'])->name('admin.system-status.scheduler');
    Route::get('/admin/system-status/module-activation', [AdminSystemStatusController::class, 'moduleActivation'])->name('admin.system-status.module-activation');
    Route::get('/admin/system-status/failed-jobs', [AdminSystemStatusController::class, 'failedJobs'])->name('admin.system-status.failed-jobs');
    Route::get('/admin/users', UserAdministrationController::class)->name('admin.users.index');
    Route::get('/admin/users/create', CreateUserAccountController::class)->name('admin.users.create');
    Route::post('/admin/users', StoreUserAccountController::class)->name('admin.users.store');
    Route::get('/admin/users/{user}/edit', EditUserAccountController::class)->name('admin.users.edit');
    Route::patch('/admin/users/{user}', UpdateUserAccountController::class)->name('admin.users.update');
    Route::post('/admin/users/{user}/activate', [UserAccountActionController::class, 'activate'])->name('admin.users.activate');
    Route::post('/admin/users/{user}/deactivate', [UserAccountActionController::class, 'deactivate'])->name('admin.users.deactivate');
    Route::post('/admin/users/{user}/verify-email', [UserAccountActionController::class, 'verifyEmail'])->name('admin.users.verify-email');
    Route::post('/admin/users/{user}/require-email-verification', [UserAccountActionController::class, 'requireEmailVerification'])->name('admin.users.require-email-verification');
    Route::post('/admin/users/{user}/resend-first-password', [UserAccountActionController::class, 'resendFirstPassword'])->name('admin.users.resend-first-password');
    Route::post('/admin/users/{user}/unlock', [UserAccountActionController::class, 'unlock'])->name('admin.users.unlock');
    Route::post('/admin/users/{user}/reset-mfa', [UserAccountActionController::class, 'resetMfa'])->middleware('admin.high-risk:'.HighRiskAdministrativeOperation::MfaReset->value)->name('admin.users.reset-mfa');
    Route::post('/admin/users/{user}/invalidate-sessions', [UserAccountActionController::class, 'invalidateSessions'])->name('admin.users.invalidate-sessions');
    Route::get('/admin/users/{user}/impersonate', [ImpersonationController::class, 'create'])->name('admin.users.impersonate');
    Route::post('/admin/users/{user}/impersonate', [ImpersonationController::class, 'store'])->name('admin.users.impersonate.store');
    Route::post('/admin/users/{user}/teams', [UserTeamMembershipController::class, 'store'])->name('admin.users.teams.store');
    Route::delete('/admin/users/{user}/teams/{team}', [UserTeamMembershipController::class, 'destroy'])->name('admin.users.teams.destroy');
    Route::patch('/admin/users/{user}/teams/{team}/authorization', [UserTeamAuthorizationController::class, 'update'])->name('admin.users.teams.authorization.update');
    Route::get('/admin/teams', TeamAdministrationController::class)->name('admin.teams.index');
    Route::get('/admin/teams/create', [TeamAdministrationController::class, 'create'])->name('admin.teams.create');
    Route::post('/admin/teams', [TeamAdministrationController::class, 'store'])->name('admin.teams.store');
    Route::get('/admin/teams/{team}/edit', [TeamAdministrationController::class, 'edit'])->name('admin.teams.edit');
    Route::patch('/admin/teams/{team}', [TeamAdministrationController::class, 'update'])->name('admin.teams.update');
    Route::post('/admin/teams/{team}/activate', [TeamAdministrationController::class, 'activate'])->name('admin.teams.activate');
    Route::post('/admin/teams/{team}/deactivate', [TeamAdministrationController::class, 'deactivate'])->name('admin.teams.deactivate');
    Route::delete('/admin/teams/{team}', [TeamAdministrationController::class, 'destroy'])->name('admin.teams.destroy');
    Route::get('/admin/managers', [ManagerHierarchyAdministrationController::class, 'index'])->name('admin.managers.index');
    Route::post('/admin/managers', [ManagerHierarchyAdministrationController::class, 'store'])->name('admin.managers.store');
    Route::patch('/admin/managers/{relationship}/end', [ManagerHierarchyAdministrationController::class, 'end'])->name('admin.managers.end');
    Route::patch('/admin/managers/head', [ManagerHierarchyAdministrationController::class, 'head'])->name('admin.managers.head.update');
    Route::get('/admin/authorization/roles', RoleAdministrationController::class)->name('admin.authorization.roles.index');
    Route::get('/admin/authorization/roles/create', CreateRoleController::class)->name('admin.authorization.roles.create');
    Route::post('/admin/authorization/roles', StoreRoleController::class)->name('admin.authorization.roles.store');
    Route::get('/admin/authorization/roles/{role}/edit', EditRoleController::class)->name('admin.authorization.roles.edit');
    Route::patch('/admin/authorization/roles/{role}', UpdateRoleController::class)->middleware('admin.high-risk:'.HighRiskAdministrativeOperation::AdministratorPermissionChange->value)->name('admin.authorization.roles.update');
    Route::delete('/admin/authorization/roles/{role}', DestroyRoleController::class)->middleware('admin.high-risk:'.HighRiskAdministrativeOperation::AdministratorPermissionChange->value)->name('admin.authorization.roles.destroy');
    Route::get('/admin/authorization/packages', OnboardingPackageAdministrationController::class)->name('admin.authorization.packages.index');
    Route::get('/admin/authorization/packages/create', CreateOnboardingPackageController::class)->name('admin.authorization.packages.create');
    Route::post('/admin/authorization/packages', StoreOnboardingPackageController::class)->name('admin.authorization.packages.store');
    Route::get('/admin/authorization/packages/{package}/edit', EditOnboardingPackageController::class)->name('admin.authorization.packages.edit');
    Route::patch('/admin/authorization/packages/{package}', UpdateOnboardingPackageController::class)->name('admin.authorization.packages.update');
    Route::delete('/admin/authorization/packages/{package}', DestroyOnboardingPackageController::class)->name('admin.authorization.packages.destroy');
    Route::get('/admin/authorization/permissions', PermissionAdministrationController::class)->name('admin.authorization.permissions.index');
    Route::get('/admin/audit', AuditBrowserController::class)->name('admin.audit.index');
    Route::get('/admin/audit/security-history', SecurityHistoryController::class)->name('admin.audit.security-history.index');
    Route::get('/admin/audit/impersonation/{session}', [AuditBrowserController::class, 'impersonationSession'])->name('admin.audit.impersonation.show');
    Route::get('/admin/rate-limits', RateLimitAdministrationController::class)->name('admin.rate-limits.index');
    Route::post('/admin/rate-limits/reset', ResetRateLimitCounterController::class)->name('admin.rate-limits.reset');
    Route::get('/admin/logs', AdminApplicationLogController::class)->name('admin.logs.index');
    Route::get('/admin/queues', [AdminFailedJobController::class, 'index'])->name('admin.queues.index');
    Route::post('/admin/queues/failed-jobs/retry', [AdminFailedJobController::class, 'retry'])->name('admin.queues.retry');
    Route::get('/admin/files', [AdminFilesController::class, 'index'])->name('admin.files.index');
    Route::post('/admin/files/{file}/rescan', [AdminFilesController::class, 'rescan'])->name('admin.files.rescan');
    Route::get('/admin/integrations', [AdminIntegrationsController::class, 'index'])->name('admin.integrations.index');
    Route::post('/admin/integrations/{integration}/test', [AdminIntegrationsController::class, 'test'])->name('admin.integrations.test');
    Route::get('/admin/modules', [ModuleActivationController::class, 'index'])->name('admin.modules.index');
    Route::get('/admin/modules/{module}', [ModuleActivationController::class, 'show'])->name('admin.modules.show');
    Route::patch('/admin/modules/{module}/global', [ModuleActivationController::class, 'updateGlobal'])->name('admin.modules.global.update');
    Route::post('/admin/modules/{module}/global/schedules', [ModuleActivationController::class, 'scheduleGlobal'])->name('admin.modules.global.schedule');
    Route::patch('/admin/modules/{module}/teams/{team}', [ModuleActivationController::class, 'updateTeam'])->name('admin.modules.team.update');
    Route::post('/admin/modules/{module}/teams/{team}/schedules', [ModuleActivationController::class, 'scheduleTeam'])->name('admin.modules.team.schedule');
    Route::delete('/admin/modules/{module}/teams/{team}', [ModuleActivationController::class, 'clearTeam'])->name('admin.modules.team.clear');
    Route::delete('/admin/modules/{module}/schedules/{schedule}', [ModuleActivationController::class, 'cancelSchedule'])->name('admin.modules.schedules.cancel');
    Route::post('/admin/table-views', [TableSavedViewController::class, 'store'])->name('admin.table-views.store');
    Route::patch('/admin/table-views/{view}', [TableSavedViewController::class, 'update'])->name('admin.table-views.update');
    Route::delete('/admin/table-views/{view}', [TableSavedViewController::class, 'destroy'])->name('admin.table-views.destroy');
    Route::post('/admin/table-views/{view}/copy', [TableSavedViewController::class, 'copy'])->name('admin.table-views.copy');
    Route::post('/admin/table-views/{view}/default', [TableSavedViewController::class, 'default'])->name('admin.table-views.default');
});
