#!/usr/bin/env php
<?php

declare(strict_types=1);

final class Phase28InventoryGenerator
{
    private string $root;

    /**
     * @var list<string>
     */
    private array $phpFiles = [];

    /**
     * @var list<string>
     */
    private array $vuePages = [];

    public function __construct(string $root)
    {
        $this->root = rtrim($root, '/');
        $this->phpFiles = $this->files('app', 'php');
        $this->vuePages = $this->files('resources/js/Pages', 'vue');
    }

    /**
     * @return array<string, mixed>
     */
    public function inventory(): array
    {
        return [
            'generated_at' => gmdate('Y-m-d\TH:i:s\Z'),
            'totals' => $this->totals(),
            'modules' => $this->modules(),
            'orphan_module_roots' => $this->orphanModuleRoots(),
            'architecture' => $this->architecture(),
            'routes' => $this->routes(),
            'frontend' => $this->frontend(),
            'migrations' => $this->migrations(),
            'audit' => $this->audit(),
            'mail' => $this->mail(),
            'seeders' => $this->seeders(),
            'runtime' => $this->runtime(),
        ];
    }

    public function json(): string
    {
        $json = json_encode($this->inventory(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

        if (! is_string($json)) {
            throw new RuntimeException('Unable to encode Phase 28 inventory as JSON.');
        }

        return $json.PHP_EOL;
    }

    public function markdown(): string
    {
        $inventory = $this->inventory();
        $totals = $inventory['totals'];

        if (! is_array($totals)) {
            throw new RuntimeException('Phase 28 inventory totals are invalid.');
        }

        $lines = [
            '# Phase 28 generated inventory',
            '',
            '> Generated by `php tools/phase28/generate-inventory.php --markdown`.',
            '',
            '## Totals',
            '',
            '| Area | Count |',
            '| --- | ---: |',
        ];

        foreach ($totals as $key => $value) {
            $lines[] = sprintf('| `%s` | %s |', $key, (string) $value);
        }

        $lines[] = '';
        $lines[] = '## Modules';
        $lines[] = '';
        $lines[] = '| Module | Category | Required | Optional | Provider | Public files | Public persistence | Actual imports |';
        $lines[] = '| --- | --- | --- | --- | --- | ---: | ---: | --- |';

        foreach ($inventory['modules'] as $module) {
            if (! is_array($module)) {
                continue;
            }

            $lines[] = sprintf(
                '| `%s` | `%s` | %s | %s | `%s` | %d | %d | %s |',
                (string) $module['key'],
                (string) $module['category'],
                $this->listCell($module['required_dependencies']),
                $this->listCell($module['optional_dependencies']),
                (string) $module['provider'],
                (int) $module['public_file_count'],
                (int) $module['public_persistence_file_count'],
                $this->listCell($module['actual_module_imports']),
            );
        }

        $routes = $inventory['routes'];
        if (! is_array($routes)) {
            throw new RuntimeException('Phase 28 route inventory is invalid.');
        }

        $lines[] = '';
        $lines[] = '## Route Prefixes';
        $lines[] = '';
        $lines[] = 'Static parser counts only literal route names in repository route files. Use `php artisan route:list --json` when framework-resolved names are required.';
        $lines[] = '';
        $lines[] = '| Prefix | Count |';
        $lines[] = '| --- | ---: |';
        foreach ($routes['app_owned_prefix_counts'] as $prefix => $count) {
            $lines[] = sprintf('| `%s` | %d |', (string) $prefix, (int) $count);
        }

        $migrations = $inventory['migrations'];
        if (! is_array($migrations)) {
            throw new RuntimeException('Phase 28 migration inventory is invalid.');
        }

        $lines[] = '';
        $lines[] = '## Migration Signals';
        $lines[] = '';
        $lines[] = '| Signal | Count |';
        $lines[] = '| --- | ---: |';
        $lines[] = sprintf('| Schema create/table operations | %d |', count($migrations['schema_operations']));
        $lines[] = sprintf('| PostgreSQL `after` usages | %d |', count($migrations['after_usages']));

        $lines[] = '';
        $lines[] = '## High-Signal Findings';
        $lines[] = '';
        $findings = [
            'public persistence classes' => 'public_persistence_class_count',
            'public persistence uses in app' => 'public_persistence_use_count',
            'raw frontend fetch calls' => 'raw_fetch_count',
            'hardcoded or raw mail signals' => 'mail_signal_count',
            'seeder direct-write signals' => 'seeder_signal_count',
            'runtime drift signals' => 'runtime_signal_count',
            'backend surface signals' => 'backend_surface_signal_count',
            'audit matrix signals' => 'audit_matrix_signal_count',
            'global provider/middleware module imports' => 'global_module_import_count',
            'migration schema operations' => 'migration_schema_operation_count',
            'migration `after` usages' => 'migration_after_usage_count',
        ];

        foreach ($findings as $label => $key) {
            $lines[] = sprintf('- %s: `%s`', $label, (string) ($totals[$key] ?? '0'));
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    public function frameworkRoutesMarkdown(): string
    {
        $routes = $this->frameworkRoutes();
        $surfaceCounts = [];

        foreach ($routes as $route) {
            $surface = (string) $route['surface'];
            $surfaceCounts[$surface] = ($surfaceCounts[$surface] ?? 0) + 1;
        }

        ksort($surfaceCounts);

        $lines = [
            '# Phase 28 framework route/view matrix',
            '',
            '> Generated by `php tools/phase28/generate-inventory.php --framework-routes-markdown`.',
            '',
            'This matrix uses `php artisan route:list --json`, so it resolves route names created from PHP constants. It remains a Phase 28 working artifact, not a permanent product contract.',
            '',
            '## Surface Counts',
            '',
            '| Surface | Routes |',
            '| --- | ---: |',
        ];

        foreach ($surfaceCounts as $surface => $count) {
            $lines[] = sprintf('| `%s` | %d |', $surface, $count);
        }

        $lines[] = '';
        $lines[] = '## Routes';
        $lines[] = '';
        $lines[] = '| Surface | Method | URI | Name | Action | Inertia pages |';
        $lines[] = '| --- | --- | --- | --- | --- | --- |';

        foreach ($routes as $route) {
            $lines[] = sprintf(
                '| `%s` | `%s` | `%s` | `%s` | `%s` | %s |',
                (string) $route['surface'],
                $this->markdownCodeText((string) $route['method']),
                (string) $route['uri'],
                (string) $route['name'],
                (string) $route['action'],
                $this->listCell($route['inertia_pages']),
            );
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    public function persistenceMarkdown(): string
    {
        $tableOperations = $this->migrationTableOperations();
        $schemaCounts = [];
        $ownerCounts = [];

        foreach ($tableOperations as $operation) {
            $schema = (string) $operation['schema'];
            $owner = (string) $operation['owner'];
            $schemaCounts[$schema] = ($schemaCounts[$schema] ?? 0) + 1;
            $ownerCounts[$owner] = ($ownerCounts[$owner] ?? 0) + 1;
        }

        ksort($schemaCounts);
        ksort($ownerCounts);

        $lines = [
            '# Phase 28 persistence matrix',
            '',
            '> Generated by `php tools/phase28/generate-inventory.php --persistence-markdown`.',
            '',
            'This static matrix resolves the simple `DatabaseSchema::*` and `*DatabaseTable::*` constants used by Atlas migrations. Dynamic config-backed tables remain marked as unresolved and require manual confirmation during the migration squash package.',
            '',
            '## Totals',
            '',
            '| Signal | Count |',
            '| --- | ---: |',
            sprintf('| Table create/table operations | %d |', count($tableOperations)),
            sprintf('| Column signals | %d |', count($this->migrationColumnSignals())),
            sprintf('| Index/unique/primary signals | %d |', count($this->migrationIndexSignals())),
            sprintf('| Foreign-key signals | %d |', count($this->migrationForeignKeySignals())),
            sprintf('| PostgreSQL `after` usages | %d |', count($this->migrationAfterUsages())),
            '',
            '## Operations By Schema',
            '',
            '| Schema | Operations |',
            '| --- | ---: |',
        ];

        foreach ($schemaCounts as $schema => $count) {
            $lines[] = sprintf('| `%s` | %d |', $schema, $count);
        }

        $lines[] = '';
        $lines[] = '## Operations By Owner';
        $lines[] = '';
        $lines[] = '| Owner | Operations |';
        $lines[] = '| --- | ---: |';

        foreach ($ownerCounts as $owner => $count) {
            $lines[] = sprintf('| `%s` | %d |', $owner, $count);
        }

        $lines[] = '';
        $lines[] = '## Table Operations';
        $lines[] = '';
        $lines[] = '| Operation | Table | Owner | File:line | Expression |';
        $lines[] = '| --- | --- | --- | --- | --- |';

        foreach ($tableOperations as $operation) {
            $lines[] = sprintf(
                '| `%s` | `%s` | `%s` | `%s:%d` | `%s` |',
                (string) $operation['operation'],
                (string) $operation['table'],
                (string) $operation['owner'],
                (string) $operation['file'],
                (int) $operation['line'],
                (string) $operation['expression'],
            );
        }

        $lines[] = '';
        $lines[] = '## Column Signals';
        $lines[] = '';
        $lines[] = '| Table | Column | Type | File:line |';
        $lines[] = '| --- | --- | --- | --- |';

        foreach ($this->migrationColumnSignals() as $column) {
            $lines[] = sprintf(
                '| `%s` | `%s` | `%s` | `%s:%d` |',
                (string) $column['table'],
                (string) $column['column'],
                (string) $column['type'],
                (string) $column['file'],
                (int) $column['line'],
            );
        }

        $lines[] = '';
        $lines[] = '## Index Signals';
        $lines[] = '';
        $lines[] = '| Table | Type | Columns/name expression | File:line |';
        $lines[] = '| --- | --- | --- | --- |';

        foreach ($this->migrationIndexSignals() as $index) {
            $lines[] = sprintf(
                '| `%s` | `%s` | `%s` | `%s:%d` |',
                (string) $index['table'],
                (string) $index['type'],
                (string) $index['expression'],
                (string) $index['file'],
                (int) $index['line'],
            );
        }

        $lines[] = '';
        $lines[] = '## Foreign-Key Signals';
        $lines[] = '';
        $lines[] = '| Table | Column | Target | File:line |';
        $lines[] = '| --- | --- | --- | --- |';

        foreach ($this->migrationForeignKeySignals() as $foreignKey) {
            $lines[] = sprintf(
                '| `%s` | `%s` | `%s` | `%s:%d` |',
                (string) $foreignKey['table'],
                (string) $foreignKey['column'],
                (string) $foreignKey['target'],
                (string) $foreignKey['file'],
                (int) $foreignKey['line'],
            );
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    public function runtimeMarkdown(): string
    {
        $signals = $this->runtimeMatrixSignals();
        $areaCounts = [];

        foreach ($signals as $signal) {
            $area = (string) $signal['area'];
            $areaCounts[$area] = ($areaCounts[$area] ?? 0) + 1;
        }

        ksort($areaCounts);

        $lines = [
            '# Phase 28 runtime/config matrix',
            '',
            '> Generated by `php tools/phase28/generate-inventory.php --runtime-markdown`.',
            '',
            'This static matrix records runtime parity signals for the Dev Container, development Compose stack, production Compose stack, PHP images, queues, scheduler, search, ClamAV, Chromium/PDF, PostgreSQL, Redis, secrets, storage, and backup. It is a Phase 28 working artifact, not a permanent runtime contract.',
            '',
            '## Signal Counts',
            '',
            '| Area | Signals |',
            '| --- | ---: |',
        ];

        foreach ($areaCounts as $area => $count) {
            $lines[] = sprintf('| `%s` | %d |', $area, $count);
        }

        $lines[] = '';
        $lines[] = '## Signals';
        $lines[] = '';
        $lines[] = '| Area | Evidence | File:line | Phase target |';
        $lines[] = '| --- | --- | --- | --- |';

        foreach ($signals as $signal) {
            $lines[] = sprintf(
                '| `%s` | %s | `%s:%d` | `%s` |',
                (string) $signal['area'],
                $this->markdownInlineCode((string) $signal['evidence']),
                (string) $signal['file'],
                (int) $signal['line'],
                (string) $signal['target'],
            );
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    public function backendSurfacesMarkdown(): string
    {
        $signals = $this->backendSurfaceSignals();
        $surfaceCounts = [];
        $typeCounts = [];

        foreach ($signals as $signal) {
            $surface = (string) $signal['surface'];
            $type = (string) $signal['type'];
            $surfaceCounts[$surface] = ($surfaceCounts[$surface] ?? 0) + 1;
            $typeCounts[$type] = ($typeCounts[$type] ?? 0) + 1;
        }

        ksort($surfaceCounts);
        ksort($typeCounts);

        $lines = [
            '# Phase 28 backend surface matrix',
            '',
            '> Generated by `php tools/phase28/generate-inventory.php --backend-surfaces-markdown`.',
            '',
            'This static matrix records backend entrypoints and producer/provider classes that need one accepted Phase 28 surface decision. It is a working inventory: HTTP route surfaces are inferred from URLs, while class-level surfaces are conservative buckets that require owner confirmation before `P28-INV-002` can close.',
            '',
            '## Signal Counts By Surface',
            '',
            '| Surface | Signals |',
            '| --- | ---: |',
        ];

        foreach ($surfaceCounts as $surface => $count) {
            $lines[] = sprintf('| `%s` | %d |', $surface, $count);
        }

        $lines[] = '';
        $lines[] = '## Signal Counts By Type';
        $lines[] = '';
        $lines[] = '| Type | Signals |';
        $lines[] = '| --- | ---: |';

        foreach ($typeCounts as $type => $count) {
            $lines[] = sprintf('| `%s` | %d |', $type, $count);
        }

        $lines[] = '';
        $lines[] = '## Signals';
        $lines[] = '';
        $lines[] = '| Owner | Surface | Type | Evidence | File:line | Target |';
        $lines[] = '| --- | --- | --- | --- | --- | --- |';

        foreach ($signals as $signal) {
            $lines[] = sprintf(
                '| `%s` | `%s` | `%s` | %s | `%s:%d` | `%s` |',
                (string) $signal['owner'],
                (string) $signal['surface'],
                (string) $signal['type'],
                $this->markdownInlineCode((string) $signal['evidence']),
                (string) $signal['file'],
                (int) $signal['line'],
                (string) $signal['target'],
            );
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    public function prepReportMarkdown(): string
    {
        $inventory = $this->inventory();
        $totals = $inventory['totals'];

        if (! is_array($totals)) {
            throw new RuntimeException('Phase 28 inventory totals are invalid.');
        }

        $moduleDrift = $this->moduleDependencyDrift();
        $moduleDriftEdgeCount = array_sum(array_map(
            static fn (array $row): int => count($row['undeclared_imports']),
            $moduleDrift,
        ));
        $auditDynamicValues = array_values(array_filter(
            $this->auditMatrixSignals(),
            static fn (array $signal): bool => str_starts_with((string) $signal['value'], '$'),
        ));

        $lines = [
            '# Phase 28 prep report',
            '',
            '> Generated by `php tools/phase28/generate-inventory.php --prep-report-markdown`.',
            '',
            'This is the Phase 28 preparation report. It summarizes the current code state before foundation repair implementation starts. It is not a claim that Phase 28 repairs are complete.',
            '',
            '## Readiness',
            '',
            '| Area | Status |',
            '| --- | --- |',
            '| Phase 28 prep | `100%` |',
            '| Automated backend/runtime/audit inventory | `ready` |',
            '| Frontend product consistency review | `recorded in phase file` |',
            '| Phase 28 implementation | `0%` |',
            '| Next implementation package | `P28-W02A` architecture guard hardening |',
            '| First frontend repair package | `P28-W05A` UI contract and glossary foundation |',
            '',
            '## Current Scale',
            '',
            '| Signal | Count |',
            '| --- | ---: |',
        ];

        foreach ([
            'modules',
            'module_php_files',
            'controllers',
            'commands',
            'jobs',
            'vue_pages',
            'migrations',
            'seeders',
            'public_persistence_class_count',
            'public_persistence_use_count',
            'global_module_import_count',
            'backend_surface_signal_count',
            'frontend_consistency_signal_count',
            'runtime_matrix_signal_count',
            'audit_matrix_signal_count',
            'migration_table_operation_count',
            'migration_after_usage_count',
        ] as $key) {
            $lines[] = sprintf('| `%s` | %d |', $key, (int) ($totals[$key] ?? 0));
        }

        $lines[] = '';
        $lines[] = '## Highest-Risk Findings';
        $lines[] = '';
        $lines[] = '| Finding | Evidence | Phase target |';
        $lines[] = '| --- | --- | --- |';
        $lines[] = sprintf('| Module dependency drift | `%d` modules with `%d` observed undeclared import edges | `P28-ARCH-001` through `P28-ARCH-014` |', count($moduleDrift), $moduleDriftEdgeCount);
        $lines[] = sprintf('| Public persistence leakage | `%d` table constant classes and `%d` app uses | `P28-ARCH-004` |', (int) ($totals['public_persistence_class_count'] ?? 0), (int) ($totals['public_persistence_use_count'] ?? 0));
        $lines[] = sprintf('| Global/shared module coupling | `%d` global provider/middleware/shared module imports | `P28-ARCH-012` through `P28-ARCH-014` |', (int) ($totals['global_module_import_count'] ?? 0));
        $lines[] = sprintf('| Migration debt | `%d` table operations, `%d` column signals, `%d` FK signals, `%d` PostgreSQL `after` usages | `P28-MIG-001` through `P28-MIG-003` |', (int) ($totals['migration_table_operation_count'] ?? 0), (int) ($totals['migration_column_signal_count'] ?? 0), (int) ($totals['migration_foreign_key_signal_count'] ?? 0), (int) ($totals['migration_after_usage_count'] ?? 0));
        $lines[] = sprintf('| Runtime drift | `%d` runtime matrix signals | `P28-RUNTIME-001` through `P28-RUNTIME-014` |', (int) ($totals['runtime_matrix_signal_count'] ?? 0));
        $lines[] = sprintf('| Audit normalization | `%d` audit matrix signals, including `%d` dynamic values requiring owner confirmation | `P28-AUDIT-001` through `P28-AUDIT-011` |', (int) ($totals['audit_matrix_signal_count'] ?? 0), count($auditDynamicValues));
        $lines[] = sprintf('| Backend surface classification | `%d` backend surface signals | `P28-INV-002`, `P28-GUARD-001`, `P28-GUARD-002` |', (int) ($totals['backend_surface_signal_count'] ?? 0));
        $lines[] = sprintf('| Frontend product consistency | `%d` Vue pages require manual naming, placement, layout, action, icon, breadcrumb, and parity review | `P28-INV-003`, `P28-UI-*`, `P28-ACTION-*`, `P28-FORM-*`, `P28-TABLE-*`, `P28-LOC-*` |', (int) ($totals['vue_pages'] ?? 0));
        $lines[] = sprintf('| Mail and seeder repair | `%d` mail signals and `%d` seeder direct-write signals | `P28-MAIL-*`, `P28-SEED-001` |', (int) ($totals['mail_signal_count'] ?? 0), (int) ($totals['seeder_signal_count'] ?? 0));

        $lines[] = '';
        $lines[] = '## Module Dependency Drift';
        $lines[] = '';
        $lines[] = '| Module | Observed undeclared imports |';
        $lines[] = '| --- | --- |';

        foreach ($moduleDrift as $row) {
            $lines[] = sprintf('| `%s` | %s |', (string) $row['module'], $this->listCell($row['undeclared_imports']));
        }

        $lines[] = '';
        $lines[] = '## First Implementation Packages';
        $lines[] = '';
        $lines[] = '1. `P28-W02A` strengthen architecture and module graph guardrails against real code.';
        $lines[] = '2. `P28-W02B` add neutral owner-owned lookup/display contracts for Identity, Teams, and Audit labels.';
        $lines[] = '3. `P28-W02C` remove the first low-risk read-only cross-module SQL/table-constant slice.';
        $lines[] = '4. `P28-W03A` validate ModuleRegistry and ModuleGate metadata once graph guards are reliable.';
        $lines[] = '5. `P28-W05A` start the frontend repair stream with the UI contract, glossary, navigation, breadcrumb, icon, action, table, form, and state guardrail foundations.';
        $lines[] = '';
        $lines[] = '## Prep Boundary';
        $lines[] = '';
        $lines[] = 'Phase 28 preparation is complete for starting implementation packages: automated backend/runtime/audit inventories are repeatable, and the manual frontend product consistency baseline is recorded in the phase file. This does not complete any repair. The generator remains temporary and must be removed or converted into permanent guardrails before final Phase 28 closure.';

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    public function frontendConsistencyMarkdown(): string
    {
        $signals = $this->frontendConsistencySignals();
        $surfaceCounts = [];
        $typeCounts = [];

        foreach ($signals as $signal) {
            $surface = (string) $signal['surface'];
            $type = (string) $signal['type'];
            $surfaceCounts[$surface] = ($surfaceCounts[$surface] ?? 0) + 1;
            $typeCounts[$type] = ($typeCounts[$type] ?? 0) + 1;
        }

        ksort($surfaceCounts);
        ksort($typeCounts);

        $lines = [
            '# Phase 28 frontend consistency matrix',
            '',
            '> Generated by `php tools/phase28/generate-inventory.php --frontend-consistency-markdown`.',
            '',
            'This matrix is an inspection aid only. It highlights frontend code-shape signals, but `P28-W01D` must still manually compare naming, placement, visual layout, actions, fields, icons, menus, breadcrumbs, states, responsive behavior, and paired workflow parity.',
            '',
            '## Signal Counts By Surface',
            '',
            '| Surface | Signals |',
            '| --- | ---: |',
        ];

        foreach ($surfaceCounts as $surface => $count) {
            $lines[] = sprintf('| `%s` | %d |', $surface, $count);
        }

        $lines[] = '';
        $lines[] = '## Signal Counts By Type';
        $lines[] = '';
        $lines[] = '| Type | Signals |';
        $lines[] = '| --- | ---: |';

        foreach ($typeCounts as $type => $count) {
            $lines[] = sprintf('| `%s` | %d |', $type, $count);
        }

        $lines[] = '';
        $lines[] = '## Signals';
        $lines[] = '';
        $lines[] = '| Surface | Type | Evidence | File:line | Target |';
        $lines[] = '| --- | --- | --- | --- | --- |';

        foreach ($signals as $signal) {
            $lines[] = sprintf(
                '| `%s` | `%s` | %s | `%s:%d` | `%s` |',
                (string) $signal['surface'],
                (string) $signal['type'],
                $this->markdownInlineCode((string) $signal['evidence']),
                (string) $signal['file'],
                (int) $signal['line'],
                (string) $signal['target'],
            );
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    public function auditMarkdown(): string
    {
        $signals = $this->auditMatrixSignals();
        $ownerCounts = [];
        $typeCounts = [];

        foreach ($signals as $signal) {
            $owner = (string) $signal['owner'];
            $type = (string) $signal['type'];
            $ownerCounts[$owner] = ($ownerCounts[$owner] ?? 0) + 1;
            $typeCounts[$type] = ($typeCounts[$type] ?? 0) + 1;
        }

        ksort($ownerCounts);
        ksort($typeCounts);

        $lines = [
            '# Phase 28 audit event matrix',
            '',
            '> Generated by `php tools/phase28/generate-inventory.php --audit-markdown`.',
            '',
            'This static matrix records AuditRecorder and SecurityAuditRecorder consumers, event constructors, and named `action`, `result`, and `source` arguments. Literal values can become catalog entries; dynamic values require manual confirmation during the audit workstream.',
            '',
            '## Signal Counts By Owner',
            '',
            '| Owner | Signals |',
            '| --- | ---: |',
        ];

        foreach ($ownerCounts as $owner => $count) {
            $lines[] = sprintf('| `%s` | %d |', $owner, $count);
        }

        $lines[] = '';
        $lines[] = '## Signal Counts By Type';
        $lines[] = '';
        $lines[] = '| Type | Signals |';
        $lines[] = '| --- | ---: |';

        foreach ($typeCounts as $type => $count) {
            $lines[] = sprintf('| `%s` | %d |', $type, $count);
        }

        $lines[] = '';
        $lines[] = '## Signals';
        $lines[] = '';
        $lines[] = '| Owner | Type | Value | File:line | Catalog target |';
        $lines[] = '| --- | --- | --- | --- | --- |';

        foreach ($signals as $signal) {
            $lines[] = sprintf(
                '| `%s` | `%s` | %s | `%s:%d` | `%s` |',
                (string) $signal['owner'],
                (string) $signal['type'],
                $this->markdownInlineCode((string) $signal['value']),
                (string) $signal['file'],
                (int) $signal['line'],
                (string) $signal['target'],
            );
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    /**
     * @return array<string, int>
     */
    private function totals(): array
    {
        return [
            'module_php_files' => count($this->files('app/Modules', 'php')),
            'controllers' => count($this->matchingFiles(['app/Modules', 'app/Shared/Presentation'], '/Controller\.php$/')),
            'commands' => count($this->matchingFiles(['app/Modules', 'app/Shared'], '/Command\.php$/')),
            'jobs' => count($this->matchingFiles(['app/Modules', 'app/Shared'], '/Job\.php$/')),
            'vue_pages' => count($this->vuePages),
            'migrations' => count($this->files('database/migrations', 'php')),
            'seeders' => count($this->files('database/seeders', 'php')),
            'modules' => count($this->moduleRoots()),
            'public_persistence_class_count' => count($this->matchingFiles(['app/Modules'], '#/Application/Public/Persistence/.*DatabaseTable\.php$#')),
            'public_persistence_use_count' => count($this->publicPersistenceUses()),
            'raw_fetch_count' => count($this->matchesInFiles($this->files('resources/js', 'ts', 'vue'), '/\bfetch\s*\(/')),
            'mail_signal_count' => count($this->mailSignals()),
            'seeder_signal_count' => count($this->seederSignals()),
            'runtime_signal_count' => count($this->runtimeSignals()),
            'runtime_matrix_signal_count' => count($this->runtimeMatrixSignals()),
            'backend_surface_signal_count' => count($this->backendSurfaceSignals()),
            'audit_matrix_signal_count' => count($this->auditMatrixSignals()),
            'frontend_consistency_signal_count' => count($this->frontendConsistencySignals()),
            'orphan_module_root_count' => count($this->orphanModuleRoots()),
            'migration_after_usage_count' => count($this->migrationAfterUsages()),
            'migration_schema_operation_count' => count($this->migrationSchemaOperations()),
            'migration_table_operation_count' => count($this->migrationTableOperations()),
            'migration_column_signal_count' => count($this->migrationColumnSignals()),
            'migration_index_signal_count' => count($this->migrationIndexSignals()),
            'migration_foreign_key_signal_count' => count($this->migrationForeignKeySignals()),
            'global_module_import_count' => count($this->globalModuleImports()),
        ];
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function modules(): array
    {
        $modules = [];

        foreach ($this->moduleRoots() as $root) {
            $moduleClass = $this->firstFile($root, '/Module\.php$/');
            $contents = $moduleClass === null ? '' : $this->read($moduleClass);
            $key = $this->matchString($contents, "/new ModuleKey\\('([^']+)'\\)/") ?? basename($root);
            $category = $this->matchString($contents, '/ModuleCategory::([A-Za-z]+)/') ?? 'Unknown';
            $provider = $this->matchString($contents, '/return\s+([A-Za-z0-9_]+)::class;\s*\}\s*public function supportsGlobalActivation/s') ?? '';
            $moduleFiles = $this->files($this->relative($root), 'php');
            $publicFiles = array_values(array_filter($moduleFiles, static fn (string $file): bool => str_contains($file, '/Application/Public/')));
            $publicPersistence = array_values(array_filter($publicFiles, static fn (string $file): bool => str_contains($file, '/Application/Public/Persistence/')));

            $modules[] = [
                'key' => $key,
                'path' => $this->relative($root),
                'category' => $category,
                'required_dependencies' => $this->dependencies($contents, 'requiredDependencies'),
                'optional_dependencies' => $this->dependencies($contents, 'optionalDependencies'),
                'provider' => $provider,
                'public_file_count' => count($publicFiles),
                'public_persistence_file_count' => count($publicPersistence),
                'actual_module_imports' => $this->actualModuleImports($moduleFiles, $root),
                'controllers' => $this->matchingFiles([$this->relative($root)], '/Controller\.php$/'),
                'commands' => $this->matchingFiles([$this->relative($root)], '/Command\.php$/'),
                'jobs' => $this->matchingFiles([$this->relative($root)], '/Job\.php$/'),
            ];
        }

        usort($modules, static fn (array $left, array $right): int => strcmp((string) $left['key'], (string) $right['key']));

        return $modules;
    }

    /**
     * @return list<array{module: string, undeclared_imports: list<string>}>
     */
    private function moduleDependencyDrift(): array
    {
        $drift = [];

        foreach ($this->modules() as $module) {
            $declared = [
                ...$module['required_dependencies'],
                ...$module['optional_dependencies'],
            ];
            $undeclared = [];

            foreach ($module['actual_module_imports'] as $import) {
                $parts = explode('\\', (string) $import);
                $importedModule = $this->camelToSnake((string) ($parts[1] ?? ''));

                if ($importedModule === '' || in_array($importedModule, $declared, true)) {
                    continue;
                }

                $undeclared[] = (string) $import;
            }

            if ($undeclared === []) {
                continue;
            }

            $drift[] = [
                'module' => (string) $module['key'],
                'undeclared_imports' => array_values(array_unique($undeclared)),
            ];
        }

        return $drift;
    }

    /**
     * @return array<string, mixed>
     */
    private function routes(): array
    {
        $routeFiles = $this->files('routes', 'php');
        $routes = [];
        $prefixCounts = [];

        foreach ($routeFiles as $file) {
            $contents = $this->read($this->root.'/'.$file);
            preg_match_all('/Route::(?:get|post|put|patch|delete)\([^;]+?->name\(([^)]+)\)/s', $contents, $matches, PREG_SET_ORDER);

            foreach ($matches as $match) {
                $name = trim($match[1]);
                $name = trim($name, "'\"");

                if ($name === '' || str_contains($name, '::')) {
                    continue;
                }

                $prefix = explode('.', $name)[0] ?: $name;
                $prefixCounts[$prefix] = ($prefixCounts[$prefix] ?? 0) + 1;
                $routes[] = [
                    'name' => $name,
                    'prefix' => $prefix,
                    'file' => $file,
                ];
            }
        }

        ksort($prefixCounts);

        return [
            'route_count' => count($routes),
            'app_owned_prefix_counts' => $prefixCounts,
            'routes' => $routes,
        ];
    }

    /**
     * @return list<array{surface: string, method: string, uri: string, name: string, action: string, inertia_pages: list<string>}>
     */
    private function frameworkRoutes(): array
    {
        $json = shell_exec('cd '.escapeshellarg($this->root).' && php artisan route:list --json 2>/dev/null');

        if (! is_string($json) || trim($json) === '') {
            throw new RuntimeException('Unable to read framework route list from artisan.');
        }

        $decoded = json_decode($json, true);

        if (! is_array($decoded)) {
            throw new RuntimeException('Unable to decode framework route list JSON.');
        }

        $routes = [];

        foreach ($decoded as $route) {
            if (! is_array($route)) {
                continue;
            }

            $action = $this->stringValue($route['action'] ?? '');
            $path = $this->stringValue($route['path'] ?? '');

            if (! str_starts_with($action, 'App\\') && ! str_starts_with($path, 'routes/')) {
                continue;
            }

            $uri = $this->stringValue($route['uri'] ?? '');

            $routes[] = [
                'surface' => $this->surfaceForUri($uri),
                'method' => $this->stringValue($route['method'] ?? ''),
                'uri' => $uri,
                'name' => $this->stringValue($route['name'] ?? 'unnamed'),
                'action' => $action,
                'inertia_pages' => $this->inertiaPagesForFrameworkRoute($action, $path),
            ];
        }

        usort($routes, static function (array $left, array $right): int {
            return [$left['surface'], $left['uri'], $left['method'], $left['name']]
                <=> [$right['surface'], $right['uri'], $right['method'], $right['name']];
        });

        return $routes;
    }

    /**
     * @return list<string>
     */
    private function inertiaPagesForFrameworkRoute(string $action, string $path): array
    {
        $files = [];

        if (str_starts_with($action, 'App\\')) {
            [$class, $method] = array_pad(explode('@', $action, 2), 2, '__invoke');
            $candidate = $this->root.'/'.str_replace('\\', '/', preg_replace('/^App\\\\/', 'app/', $class) ?? $class).'.php';

            if (is_file($candidate)) {
                return $this->inertiaPagesForPhpFile($candidate, $method);
            }
        }

        $routeLine = $this->lineNumberFromPath($path);
        $routePath = preg_replace('/:\d+$/', '', $path) ?? $path;

        if (str_starts_with($routePath, 'routes/') && is_file($this->root.'/'.$routePath)) {
            return $this->inertiaPagesForPhpFile($this->root.'/'.$routePath, null, $routeLine);
        }

        $pages = [];

        foreach (array_unique($files) as $file) {
            array_push($pages, ...$this->inertiaPagesForPhpFile($file));
        }

        sort($pages);

        return array_values(array_unique($pages));
    }

    /**
     * @return list<string>
     */
    private function inertiaPagesForPhpFile(string $file, ?string $method = null, ?int $line = null): array
    {
        $contents = $this->read($file);

        if ($method !== null) {
            $methodBody = $this->methodBody($contents, $method);

            if ($methodBody !== null) {
                $contents = $methodBody;
            }
        }

        if ($method === null && $line !== null) {
            $contents = $this->lineWindow($contents, $line);
        }

        preg_match_all('/Inertia::render\(\s*[\'"]([^\'"]+)[\'"]/', $contents, $matches);
        $pages = $matches[1] ?? [];
        sort($pages);

        return array_values(array_unique($pages));
    }

    private function methodBody(string $contents, string $method): ?string
    {
        if (preg_match('/function\s+'.preg_quote($method, '/').'\s*\([^)]*\)\s*(?::\s*[^{}]+)?\{/s', $contents, $match, PREG_OFFSET_CAPTURE) !== 1) {
            return null;
        }

        $start = ($match[0][1] ?? 0) + strlen($match[0][0]);
        $depth = 1;
        $length = strlen($contents);

        for ($index = $start; $index < $length; $index++) {
            if ($contents[$index] === '{') {
                $depth++;
            }

            if ($contents[$index] === '}') {
                $depth--;

                if ($depth === 0) {
                    return substr($contents, $start, $index - $start);
                }
            }
        }

        return null;
    }

    private function lineNumberFromPath(string $path): ?int
    {
        if (preg_match('/:(\d+)$/', $path, $match) !== 1) {
            return null;
        }

        return (int) $match[1];
    }

    private function lineWindow(string $contents, int $line): string
    {
        $lines = explode("\n", $contents);
        $start = max(0, $line - 1);
        $window = [];

        for ($index = $start; $index < min(count($lines), $start + 24); $index++) {
            if ($index > $start && preg_match('/^\s*Route::/', $lines[$index]) === 1) {
                break;
            }

            $window[] = $lines[$index];
        }

        return implode("\n", $window);
    }

    private function surfaceForUri(string $uri): string
    {
        if ($uri === 'health/live' || $uri === 'health/ready') {
            return 'operations';
        }

        if ($uri === '/' || str_starts_with($uri, 'user') || str_starts_with($uri, 'team') || str_starts_with($uri, 'time-tracking')) {
            return 'regular_user';
        }

        if (str_starts_with($uri, 'manager')) {
            return 'manager';
        }

        if (str_starts_with($uri, 'admin') || str_starts_with($uri, 'admin-mode') || str_starts_with($uri, 'impersonation')) {
            return 'administrator';
        }

        if (str_starts_with($uri, 'exports') || str_starts_with($uri, 'notifications/realtime')) {
            return 'internal';
        }

        return 'regular_user';
    }

    /**
     * @return array<string, mixed>
     */
    private function frontend(): array
    {
        $pages = array_map(
            fn (string $file): string => substr($file, strlen('resources/js/Pages/'), -4),
            $this->vuePages,
        );

        sort($pages);

        return [
            'page_count' => count($pages),
            'pages' => $pages,
            'inertia_render_pages' => $this->inertiaRenderPages(),
            'raw_fetch' => $this->matchesInFiles($this->files('resources/js', 'ts', 'vue'), '/\bfetch\s*\(/'),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function architecture(): array
    {
        return [
            'public_persistence_uses' => $this->publicPersistenceUses(),
            'global_module_imports' => $this->globalModuleImports(),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function migrations(): array
    {
        return [
            'schema_operations' => $this->migrationSchemaOperations(),
            'table_operations' => $this->migrationTableOperations(),
            'column_signals' => $this->migrationColumnSignals(),
            'index_signals' => $this->migrationIndexSignals(),
            'foreign_key_signals' => $this->migrationForeignKeySignals(),
            'after_usages' => $this->migrationAfterUsages(),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function audit(): array
    {
        return [
            'event_producers' => $this->matchesInFiles($this->phpFiles, '/new\s+(?:AuditEvent|SecurityAuditEvent)\s*\(/'),
            'action_strings' => $this->matchesInFiles($this->phpFiles, '/action:\s*[\'"]([^\'"]+)[\'"]/'),
            'result_strings' => $this->matchesInFiles($this->phpFiles, '/result:\s*[\'"]([^\'"]+)[\'"]/'),
            'matrix_signals' => $this->auditMatrixSignals(),
        ];
    }

    /**
     * @return list<array{owner: string, surface: string, type: string, evidence: string, file: string, line: int, target: string}>
     */
    private function backendSurfaceSignals(): array
    {
        $signals = [];

        foreach ($this->frameworkRoutes() as $route) {
            $action = (string) $route['action'];
            $file = 'artisan route:list';
            $line = 1;

            if (str_starts_with($action, 'App\\')) {
                [$class] = explode('@', $action, 2);
                $candidate = $this->root.'/'.str_replace('\\', '/', preg_replace('/^App\\\\/', 'app/', $class) ?? $class).'.php';

                if (is_file($candidate)) {
                    $file = $this->relative($candidate);
                    $line = $this->classLine($file);
                }
            }

            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($file),
                (string) $route['surface'],
                'http_route',
                sprintf('%s %s %s -> %s', (string) $route['method'], (string) $route['uri'], (string) $route['name'], $action),
                $file,
                $line,
            );
        }

        foreach ($this->matchingFiles(['app/Modules', 'app/Shared/Presentation'], '/Controller\.php$/') as $file) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($file),
                $this->surfaceForPath($file),
                'controller',
                $this->className($file),
                $file,
                $this->classLine($file),
            );
        }

        foreach ($this->matchingFiles(['app/Modules', 'app/Shared'], '/Command\.php$/') as $file) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($file),
                str_contains($file, '/Presentation/Console/') || str_contains($file, '/Shared/Presentation/Console/') ? 'cli_operations' : 'internal_application',
                'command_class',
                $this->className($file).' '.$this->consoleSignature($file),
                $file,
                $this->classLine($file),
            );
        }

        foreach ($this->matchingFiles(['app/Modules', 'app/Shared'], '/Job\.php$/') as $file) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($file),
                'worker_scheduler',
                'job_class',
                $this->className($file),
                $file,
                $this->classLine($file),
            );
        }

        foreach ($this->matchesInFiles([...$this->files('routes', 'php'), ...$this->existingFiles(['bootstrap/app.php'])], '/Schedule::|->command\s*\(|->job\s*\(|Artisan::command/') as $match) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($match['file']),
                'worker_scheduler',
                'schedule_signal',
                $match['match'],
                $match['file'],
                $match['line'],
            );
        }

        foreach ($this->matchesInFiles($this->phpFiles, '/implements\s+ShouldQueue|->onQueue\s*\(|dispatch\s*\(/') as $match) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($match['file']),
                'worker_scheduler',
                'queue_signal',
                $match['match'],
                $match['file'],
                $match['line'],
            );
        }

        foreach ($this->mailSignals() as $match) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($match['file']),
                'mail',
                'mail_signal',
                $match['match'],
                $match['file'],
                $match['line'],
            );
        }

        foreach ($this->matchingFiles(['app/Modules', 'app/Shared'], '/Notification\.php$/') as $file) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($file),
                'mail_realtime',
                'notification_class',
                $this->className($file),
                $file,
                $this->classLine($file),
            );
        }

        foreach ($this->matchingFiles(['app/Modules', 'app/Shared'], '/DataTableExportProvider\.php$/') as $file) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($file),
                str_contains($file, '/Admin') ? 'administrator' : 'internal_application',
                'export_provider',
                $this->className($file),
                $file,
                $this->classLine($file),
            );
        }

        foreach ($this->matchesInFiles($this->phpFiles, '/implements\s+ManagedProcessHandler|ManagedProcessRunner|ManagedProcessReporter/') as $match) {
            $signals[] = $this->backendSurfaceSignal(
                $this->ownerForPath($match['file']),
                'worker_scheduler',
                'managed_process_signal',
                $match['match'],
                $match['file'],
                $match['line'],
            );
        }

        foreach ($this->files('database/seeders', 'php') as $file) {
            $signals[] = $this->backendSurfaceSignal(
                'seeders',
                'seed_test_demo',
                'seeder_class',
                $this->className($file),
                $file,
                $this->classLine($file),
            );
        }

        usort($signals, static function (array $left, array $right): int {
            return [$left['surface'], $left['owner'], $left['type'], $left['file'], $left['line'], $left['evidence']]
                <=> [$right['surface'], $right['owner'], $right['type'], $right['file'], $right['line'], $right['evidence']];
        });

        return $signals;
    }

    /**
     * @return array{owner: string, surface: string, type: string, evidence: string, file: string, line: int, target: string}
     */
    private function backendSurfaceSignal(string $owner, string $surface, string $type, string $evidence, string $file, int $line): array
    {
        return [
            'owner' => $owner,
            'surface' => $surface,
            'type' => $type,
            'evidence' => $this->compactExpression($evidence),
            'file' => $file,
            'line' => $line,
            'target' => $this->backendSurfaceTarget($type, $surface),
        ];
    }

    private function backendSurfaceTarget(string $type, string $surface): string
    {
        if ($type === 'http_route' || $type === 'controller') {
            return 'P28-INV-002/P28-INV-003/P28-GUARD-001';
        }

        return match ($surface) {
            'worker_scheduler' => 'P28-INV-002/P28-RUNTIME-005/P28-RUNTIME-006',
            'mail', 'mail_realtime' => 'P28-INV-002/P28-MAIL-001/P28-MAIL-002',
            'seed_test_demo' => 'P28-INV-002/P28-SEED-001',
            'administrator' => 'P28-INV-002/P28-TABLE-001/P28-GUARD-001',
            default => 'P28-INV-002',
        };
    }

    private function surfaceForPath(string $file): string
    {
        if (str_contains($file, '/Presentation/Console/')) {
            return 'cli_operations';
        }

        if (str_contains($file, '/Presentation/Jobs/') || str_contains($file, '/Infrastructure/Runtime/')) {
            return 'worker_scheduler';
        }

        if (str_contains($file, '/Admin') || str_contains($file, '/Administration')) {
            return 'administrator';
        }

        if (str_contains($file, '/Manager')) {
            return 'manager';
        }

        if (str_contains($file, '/User') || str_contains($file, '/Notification')) {
            return 'regular_user';
        }

        if (str_contains($file, '/Health/')) {
            return 'operations';
        }

        return 'internal_application';
    }

    private function className(string $file): string
    {
        $contents = $this->read($this->root.'/'.$file);

        return $this->matchString($contents, '/\b(?:final\s+)?(?:readonly\s+)?class\s+([A-Za-z0-9_]+)/') ?? basename($file, '.php');
    }

    private function classLine(string $file): int
    {
        $lines = explode("\n", $this->read($this->root.'/'.$file));

        foreach ($lines as $index => $line) {
            if (preg_match('/\b(?:final\s+)?(?:readonly\s+)?class\s+[A-Za-z0-9_]+/', $line) === 1) {
                return $index + 1;
            }
        }

        return 1;
    }

    private function consoleSignature(string $file): string
    {
        $contents = $this->read($this->root.'/'.$file);
        $signature = $this->matchString($contents, '/protected\s+\$signature\s*=\s*[\'"]([^\'"]+)[\'"]/');

        return $signature === null ? '' : '['.$signature.']';
    }

    /**
     * @return list<array{owner: string, type: string, value: string, file: string, line: int, target: string}>
     */
    private function auditMatrixSignals(): array
    {
        $signals = [];
        $files = [
            ...$this->phpFiles,
            ...$this->files('database/seeders', 'php'),
        ];

        foreach ($files as $file) {
            $lines = explode("\n", $this->read($this->root.'/'.$file));
            $owner = $this->ownerForPath($file);

            foreach ($lines as $index => $line) {
                if (preg_match('/use App\\\\Modules\\\\Core\\\\Audit\\\\Application\\\\Public\\\\Contracts\\\\AuditRecorder;/', $line) === 1) {
                    $signals[] = $this->auditSignal($owner, 'recorder_contract', 'AuditRecorder', $file, $index + 1);
                }

                if (preg_match('/use App\\\\Modules\\\\Core\\\\Identity\\\\Application\\\\Public\\\\Contracts\\\\SecurityAuditRecorder;/', $line) === 1) {
                    $signals[] = $this->auditSignal($owner, 'recorder_contract', 'SecurityAuditRecorder', $file, $index + 1);
                }

                if (preg_match('/new\s+(AuditEvent|SecurityAuditEvent)\s*\(/', $line, $match) === 1) {
                    $signals[] = $this->auditSignal($owner, 'event_constructor', $match[1], $file, $index + 1);
                }

                foreach (['action', 'result', 'source'] as $argument) {
                    $value = $this->namedArgumentValue($line, $argument);

                    if ($value === null) {
                        continue;
                    }

                    $signals[] = $this->auditSignal($owner, $argument, $value, $file, $index + 1);
                }
            }
        }

        usort($signals, static function (array $left, array $right): int {
            return [$left['owner'], $left['type'], $left['file'], $left['line'], $left['value']]
                <=> [$right['owner'], $right['type'], $right['file'], $right['line'], $right['value']];
        });

        return $signals;
    }

    /**
     * @return list<array{surface: string, type: string, evidence: string, file: string, line: int, target: string}>
     */
    private function frontendConsistencySignals(): array
    {
        $signals = [];
        $pagePatterns = [
            ['type' => 'app_layout', 'pattern' => '/<AppLayout\b/', 'target' => 'P28-INV-003/P28-UI-001/P28-NAV-001'],
            ['type' => 'auth_layout', 'pattern' => '/<AuthLayout\b/', 'target' => 'P28-INV-003/P28-UI-001'],
            ['type' => 'head_title', 'pattern' => '/<Head\s+[^>]*:title=/', 'target' => 'P28-INV-003/P28-UI-002'],
            ['type' => 'title_icon', 'pattern' => '/:title-icon=/', 'target' => 'P28-INV-003/P28-UI-002/P28-NAV-001'],
            ['type' => 'datatable', 'pattern' => '/<DataTable\b|DataTableColumn|DataTableAction|DataTableBulkAction/', 'target' => 'P28-INV-003/P28-TABLE-001/P28-ACTION-001'],
            ['type' => 'record_actions', 'pattern' => '/<RecordActions\b|DataTableAction/', 'target' => 'P28-ACTION-001/P28-ACTION-002'],
            ['type' => 'form_actions', 'pattern' => '/<FormActions\b|<DialogFormActions\b/', 'target' => 'P28-FORM-001/P28-FORM-002'],
            ['type' => 'surface_card', 'pattern' => '/<SurfaceCard\b/', 'target' => 'P28-UI-001/P28-FORM-001'],
            ['type' => 'local_status_logic', 'pattern' => '/statusLabel|StatusLabel|statusOptions|StatusOptions|managerType|decisionState|scanState|enabledLabel|timeTrackingStatusLabel/', 'target' => 'P28-TABLE-008/P28-TABLE-009/P28-TT-002'],
            ['type' => 'local_option_builder', 'pattern' => '/computed<.*Option|const\s+[A-Za-z0-9_]*Options\s*=|options:\s*\[/', 'target' => 'P28-FORM-001/P28-AUTH-003/P28-TABLE-006'],
            ['type' => 'raw_fetch', 'pattern' => '/\bfetch\s*\(/', 'target' => 'P28-FORM-005/P28-GUARD-001'],
            ['type' => 'native_dialog', 'pattern' => '/\b(?:alert|confirm)\s*\(/', 'target' => 'P28-ACTION-003/P28-GUARD-001'],
            ['type' => 'technical_token_column', 'pattern' => '/publicId|public_id|moduleKey|module_key|sourceType|exactSeconds|sessionId|eventType/', 'target' => 'P28-TABLE-004/P28-TABLE-005/P28-TABLE-009'],
        ];

        foreach ($this->vuePages as $file) {
            $lineCount = substr_count($this->read($this->root.'/'.$file), "\n") + 1;
            $signals[] = $this->frontendConsistencySignal(
                $this->frontendSurfaceForPage($file),
                'page_inventory',
                sprintf('%s lines', $lineCount),
                $file,
                1,
                'P28-INV-003',
            );

            if ($lineCount >= 300) {
                $signals[] = $this->frontendConsistencySignal(
                    $this->frontendSurfaceForPage($file),
                    'large_page',
                    sprintf('%s lines', $lineCount),
                    $file,
                    1,
                    'P28-UI-001/P28-TABLE-002/P28-TT-002',
                );
            }

            $lines = explode("\n", $this->read($this->root.'/'.$file));

            foreach ($lines as $index => $line) {
                foreach ($pagePatterns as $definition) {
                    if (preg_match($definition['pattern'], $line) !== 1) {
                        continue;
                    }

                    $signals[] = $this->frontendConsistencySignal(
                        $this->frontendSurfaceForPage($file),
                        $definition['type'],
                        trim($line),
                        $file,
                        $index + 1,
                        $definition['target'],
                    );
                }
            }
        }

        foreach ($this->existingFiles(['resources/js/Components/Sidebar.vue', 'resources/js/Components/MobileNavigation.vue', 'resources/js/Components/TopBar.vue']) as $file) {
            $lines = explode("\n", $this->read($this->root.'/'.$file));

            foreach ($lines as $index => $line) {
                if (preg_match('/href:\s*[\'"][^\'"]+|canSee(?:Admin|Application)Route|navigation\.|ShellSubnavigation|mode:/', $line) !== 1) {
                    continue;
                }

                $signals[] = $this->frontendConsistencySignal(
                    'navigation',
                    'navigation_registry_signal',
                    trim($line),
                    $file,
                    $index + 1,
                    'P28-INV-003/P28-NAV-001/P28-NAV-002/P28-GUARD-001',
                );
            }
        }

        usort($signals, static function (array $left, array $right): int {
            return [$left['surface'], $left['type'], $left['file'], $left['line'], $left['evidence']]
                <=> [$right['surface'], $right['type'], $right['file'], $right['line'], $right['evidence']];
        });

        return $signals;
    }

    /**
     * @return array{surface: string, type: string, evidence: string, file: string, line: int, target: string}
     */
    private function frontendConsistencySignal(string $surface, string $type, string $evidence, string $file, int $line, string $target): array
    {
        return [
            'surface' => $surface,
            'type' => $type,
            'evidence' => $this->compactExpression($evidence),
            'file' => $file,
            'line' => $line,
            'target' => $target,
        ];
    }

    private function frontendSurfaceForPage(string $file): string
    {
        if (str_contains($file, '/Pages/Admin/')) {
            return 'administrator';
        }

        if (str_contains($file, '/Pages/Manager/')) {
            return 'manager';
        }

        if (str_contains($file, '/Pages/Auth/')) {
            return 'auth';
        }

        if (str_contains($file, '/Pages/TimeTracking/Admin')) {
            return 'administrator_time_tracking';
        }

        if (str_contains($file, '/Pages/TimeTracking/Manager')) {
            return 'manager_time_tracking';
        }

        if (str_contains($file, '/Pages/TimeTracking/')) {
            return 'regular_user_time_tracking';
        }

        return 'regular_user';
    }

    /**
     * @return array{owner: string, type: string, value: string, file: string, line: int, target: string}
     */
    private function auditSignal(string $owner, string $type, string $value, string $file, int $line): array
    {
        return [
            'owner' => $owner,
            'type' => $type,
            'value' => $this->auditSignalValue($value),
            'file' => $file,
            'line' => $line,
            'target' => $this->auditTargetForOwner($owner),
        ];
    }

    private function auditSignalValue(string $value): string
    {
        $value = $this->compactExpression($value);

        if (preg_match('/^[\'"]([^\'"]+)[\'"]$/', $value, $match) === 1) {
            return $match[1];
        }

        return $value;
    }

    private function namedArgumentValue(string $line, string $argument): ?string
    {
        $trimmed = trim($line);

        if ($trimmed === '' || str_starts_with($trimmed, '*') || str_starts_with($trimmed, '/**') || str_starts_with($trimmed, '/*') || str_starts_with($trimmed, '//')) {
            return null;
        }

        if (preg_match('/\b'.preg_quote($argument, '/').':\s*(?<value>[^,]+),?/', $line, $match) !== 1) {
            return null;
        }

        return $match['value'];
    }

    private function ownerForPath(string $file): string
    {
        if (str_starts_with($file, 'app/Modules/')) {
            $parts = explode('/', $file);

            return $this->camelToSnake((string) ($parts[3] ?? 'unknown'));
        }

        if (str_starts_with($file, 'app/Shared/')) {
            return 'shared';
        }

        if (str_starts_with($file, 'app/Providers/') || str_starts_with($file, 'app/Http/')) {
            return 'global';
        }

        if (str_starts_with($file, 'database/seeders/')) {
            return 'seeders';
        }

        return 'unknown';
    }

    private function auditTargetForOwner(string $owner): string
    {
        return match ($owner) {
            'audit' => 'P28-AUDIT-001/P28-AUDIT-002/P28-MODAUD-005',
            'authorization' => 'P28-AUDIT-001/P28-AUTH-003/P28-MODAUD-002',
            'files' => 'P28-AUDIT-001/P28-MODAUD-009',
            'identity' => 'P28-AUDIT-001/P28-MODAUD-001',
            'integrations' => 'P28-AUDIT-004/P28-MODAUD-013',
            'privacy' => 'P28-AUDIT-001/P28-MODAUD-011',
            'settings' => 'P28-AUDIT-001/P28-MODAUD-006',
            'shared' => 'P28-AUDIT-001/P28-MODAUD-019',
            'teams' => 'P28-AUDIT-001/P28-MODAUD-003',
            'time_tracking' => 'P28-AUDIT-005/P28-TT-004/P28-MODAUD-018',
            'users' => 'P28-AUDIT-001/P28-MODAUD-004',
            'seeders' => 'P28-SEED-001/P28-AUDIT-001',
            default => 'P28-AUDIT-001',
        };
    }

    /**
     * @return array<string, mixed>
     */
    private function mail(): array
    {
        return [
            'signals' => $this->mailSignals(),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function seeders(): array
    {
        return [
            'signals' => $this->seederSignals(),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function runtime(): array
    {
        return [
            'signals' => $this->runtimeSignals(),
        ];
    }

    /**
     * @return list<string>
     */
    private function moduleRoots(): array
    {
        $roots = [];

        foreach (['app/Modules/Core', 'app/Modules/Optional', 'app/Modules/Application'] as $base) {
            $absolute = $this->root.'/'.$base;
            if (! is_dir($absolute)) {
                continue;
            }

            foreach (scandir($absolute) ?: [] as $entry) {
                if ($entry === '.' || $entry === '..' || str_starts_with($entry, '.')) {
                    continue;
                }

                $path = $absolute.'/'.$entry;
                if (is_dir($path) && $this->firstFile($path, '/Module\.php$/') !== null) {
                    $roots[] = $path;
                }
            }
        }

        sort($roots);

        return $roots;
    }

    /**
     * @return list<string>
     */
    private function orphanModuleRoots(): array
    {
        $roots = [];

        foreach (['app/Modules/Core', 'app/Modules/Optional', 'app/Modules/Application'] as $base) {
            $absolute = $this->root.'/'.$base;
            if (! is_dir($absolute)) {
                continue;
            }

            foreach (scandir($absolute) ?: [] as $entry) {
                if ($entry === '.' || $entry === '..' || str_starts_with($entry, '.')) {
                    continue;
                }

                $path = $absolute.'/'.$entry;
                if (is_dir($path) && $this->firstFile($path, '/Module\.php$/') === null) {
                    $roots[] = $this->relative($path);
                }
            }
        }

        sort($roots);

        return $roots;
    }

    /**
     * @return list<string>
     */
    private function dependencies(string $contents, string $method): array
    {
        if (preg_match('/function\s+'.$method.'\(\):\s+array\s*\{(?<body>.*?)\n\s*\}/s', $contents, $match) !== 1) {
            return [];
        }

        preg_match_all("/new ModuleKey\\('([^']+)'\\)/", $match['body'], $matches);
        $dependencies = $matches[1] ?? [];
        sort($dependencies);

        return array_values(array_unique($dependencies));
    }

    /**
     * @param  list<string>  $files
     * @return list<string>
     */
    private function actualModuleImports(array $files, string $moduleRoot): array
    {
        $ownRelativeRoot = $this->relative($moduleRoot);
        $ownParts = explode('/', $ownRelativeRoot);
        $ownModule = ($ownParts[2] ?? '').'\\'.($ownParts[3] ?? '');
        $imports = [];

        foreach ($files as $file) {
            $contents = $this->read($this->root.'/'.$file);
            preg_match_all('/App\\\\Modules\\\\(Core|Optional|Application)\\\\([A-Za-z0-9_]+)/', $contents, $matches, PREG_SET_ORDER);

            foreach ($matches as $match) {
                $module = $match[1].'\\'.$match[2];

                if ($module === $ownModule) {
                    continue;
                }

                $imports[] = $module;
            }
        }

        sort($imports);

        return array_values(array_unique($imports));
    }

    /**
     * @return list<string>
     */
    private function inertiaRenderPages(): array
    {
        $pages = [];

        foreach ($this->phpFiles as $file) {
            $contents = $this->read($this->root.'/'.$file);
            preg_match_all('/Inertia::render\(\s*[\'"]([^\'"]+)[\'"]/', $contents, $matches);

            foreach ($matches[1] ?? [] as $page) {
                $pages[] = $page;
            }
        }

        foreach ($this->files('routes', 'php') as $file) {
            $contents = $this->read($this->root.'/'.$file);
            preg_match_all('/Inertia::render\(\s*[\'"]([^\'"]+)[\'"]/', $contents, $matches);

            foreach ($matches[1] ?? [] as $page) {
                $pages[] = $page;
            }
        }

        sort($pages);

        return array_values(array_unique($pages));
    }

    /**
     * @return list<array{file: string, line: int, match: string}>
     */
    private function publicPersistenceUses(): array
    {
        return $this->matchesInFiles($this->phpFiles, '/Application\\\\Public\\\\Persistence\\\\[A-Za-z0-9_]+DatabaseTable/');
    }

    /**
     * @return list<array{file: string, line: int, match: string}>
     */
    private function globalModuleImports(): array
    {
        return $this->matchesInFiles(
            [
                ...$this->files('app/Providers', 'php'),
                ...$this->files('app/Http/Middleware', 'php'),
                ...$this->files('app/Shared', 'php'),
            ],
            '/App\\\\Modules\\\\(?:Core|Optional|Application)\\\\[A-Za-z0-9_\\\\]+/',
        );
    }

    /**
     * @return list<array{file: string, line: int, match: string}>
     */
    private function migrationSchemaOperations(): array
    {
        return $this->matchesInFiles(
            $this->files('database/migrations', 'php'),
            '/Schema::(?:create|table)\(([^,]+),/',
        );
    }

    /**
     * @return list<array{file: string, line: int, match: string}>
     */
    private function migrationAfterUsages(): array
    {
        return $this->matchesInFiles(
            $this->files('database/migrations', 'php'),
            '/->after\s*\(/',
        );
    }

    /**
     * @return list<array{operation: string, table: string, schema: string, owner: string, expression: string, file: string, line: int}>
     */
    private function migrationTableOperations(): array
    {
        $operations = [];

        foreach ($this->migrationBlocks() as $block) {
            $table = $this->resolveTableExpression($block['expression']);
            $schema = $this->schemaForTable($table);

            $operations[] = [
                'operation' => $block['operation'],
                'table' => $table,
                'schema' => $schema,
                'owner' => $this->ownerForSchema($schema),
                'expression' => $block['expression'],
                'file' => $block['file'],
                'line' => $block['line'],
            ];
        }

        return $operations;
    }

    /**
     * @return list<array{table: string, column: string, type: string, file: string, line: int}>
     */
    private function migrationColumnSignals(): array
    {
        $columns = [];
        $nonColumns = [
            'foreign' => true,
            'index' => true,
            'primary' => true,
            'unique' => true,
        ];

        foreach ($this->migrationBlocks() as $block) {
            $table = $this->resolveTableExpression($block['expression']);

            foreach ($block['lines'] as $lineOffset => $line) {
                if (preg_match('/\$table->([A-Za-z][A-Za-z0-9_]*)\((?<args>[^;]*)\)/', $line, $match) !== 1) {
                    continue;
                }

                $type = $match[1];
                if (isset($nonColumns[$type])) {
                    continue;
                }

                $column = $this->firstStringArgument($match['args']) ?? $this->implicitColumnForBlueprintMethod($type);

                $columns[] = [
                    'table' => $table,
                    'column' => $column,
                    'type' => $type,
                    'file' => $block['file'],
                    'line' => $block['line'] + $lineOffset,
                ];
            }
        }

        return $columns;
    }

    /**
     * @return list<array{table: string, type: string, expression: string, file: string, line: int}>
     */
    private function migrationIndexSignals(): array
    {
        $indexes = [];

        foreach ($this->migrationBlocks() as $block) {
            $table = $this->resolveTableExpression($block['expression']);

            foreach ($block['lines'] as $lineOffset => $line) {
                if (preg_match('/\$table->(index|unique|primary)\((?<args>[^;]*)\)/', $line, $match) !== 1) {
                    continue;
                }

                $indexes[] = [
                    'table' => $table,
                    'type' => $match[1],
                    'expression' => $this->compactExpression($match['args']),
                    'file' => $block['file'],
                    'line' => $block['line'] + $lineOffset,
                ];
            }
        }

        return $indexes;
    }

    /**
     * @return list<array{table: string, column: string, target: string, file: string, line: int}>
     */
    private function migrationForeignKeySignals(): array
    {
        $foreignKeys = [];

        foreach ($this->migrationBlocks() as $block) {
            $table = $this->resolveTableExpression($block['expression']);

            foreach ($block['lines'] as $lineOffset => $line) {
                if (preg_match('/\$table->foreignId\([\'"]([^\'"]+)[\'"]\)(?<tail>.*?);/', $line, $match) === 1) {
                    if (preg_match('/->constrained\((?<target>[^)]*)\)/', $match['tail'], $targetMatch) !== 1) {
                        continue;
                    }

                    $foreignKeys[] = [
                        'table' => $table,
                        'column' => $match[1],
                        'target' => $this->resolveTableExpression($targetMatch['target']),
                        'file' => $block['file'],
                        'line' => $block['line'] + $lineOffset,
                    ];
                }

                if (preg_match('/\$table->foreign\([\'"]([^\'"]+)[\'"]\)/', $line, $match) === 1) {
                    $joined = implode(' ', array_slice($block['lines'], $lineOffset, 4));
                    $target = 'unresolved';

                    if (preg_match('/->on\((?<target>[^)]*)\)/', $joined, $targetMatch) === 1) {
                        $target = $this->resolveTableExpression($targetMatch['target']);
                    }

                    $foreignKeys[] = [
                        'table' => $table,
                        'column' => $match[1],
                        'target' => $target,
                        'file' => $block['file'],
                        'line' => $block['line'] + $lineOffset,
                    ];
                }
            }
        }

        return $foreignKeys;
    }

    /**
     * @return list<array{operation: string, expression: string, file: string, line: int, lines: list<string>}>
     */
    private function migrationBlocks(): array
    {
        $blocks = [];

        foreach ($this->files('database/migrations', 'php') as $file) {
            $lines = explode("\n", $this->read($this->root.'/'.$file));
            $current = null;

            foreach ($lines as $index => $line) {
                if ($current === null && preg_match('/Schema::(create|table)\((?<expression>[^,]+),/', $line, $match) === 1) {
                    $current = [
                        'operation' => $match[1],
                        'expression' => $this->compactExpression($match['expression']),
                        'file' => $file,
                        'line' => $index + 1,
                        'lines' => [$line],
                    ];

                    continue;
                }

                if ($current === null) {
                    continue;
                }

                $current['lines'][] = $line;

                if (preg_match('/^\s*\}\);/', $line) === 1) {
                    $blocks[] = $current;
                    $current = null;
                }
            }
        }

        return $blocks;
    }

    private function resolveTableExpression(string $expression): string
    {
        $expression = $this->compactExpression($expression);

        if (preg_match('/^[\'"]([^\'"]+)[\'"]$/', $expression, $match) === 1) {
            return $match[1];
        }

        if (preg_match('/^([A-Za-z0-9_]+)::([A-Z0-9_]+)$/', $expression, $match) === 1) {
            $key = $match[1].'::'.$match[2];

            return $this->databaseTableConstants()[$key] ?? 'unresolved:'.$expression;
        }

        if (preg_match('/^DatabaseSchema::([A-Z0-9_]+)\.\'[.]([^\'"]+)\'$/', $expression, $match) === 1) {
            $schema = $this->databaseSchemaConstants()[$match[1]] ?? 'unresolved_schema:'.$match[1];

            return $schema.'.'.$match[2];
        }

        return 'unresolved:'.$expression;
    }

    /**
     * @return array<string, string>
     */
    private function databaseTableConstants(): array
    {
        $schemas = $this->databaseSchemaConstants();
        $constants = [];

        foreach ([...$this->files('app/Shared/Infrastructure/Database', 'php'), ...$this->matchingFiles(['app/Modules'], '#/Application/Public/Persistence/.*DatabaseTable\.php$#')] as $file) {
            $contents = $this->read($this->root.'/'.$file);

            if (preg_match('/final class ([A-Za-z0-9_]+)/', $contents, $classMatch) !== 1) {
                continue;
            }

            preg_match_all("/public const ([A-Z0-9_]+) = DatabaseSchema::([A-Z0-9_]+)\\.('[^']+');/", $contents, $matches, PREG_SET_ORDER);

            foreach ($matches as $match) {
                $schema = $schemas[$match[2]] ?? 'unresolved_schema:'.$match[2];
                $table = trim($match[3], "'");
                $constants[$classMatch[1].'::'.$match[1]] = $schema.$table;
            }
        }

        ksort($constants);

        return $constants;
    }

    /**
     * @return array<string, string>
     */
    private function databaseSchemaConstants(): array
    {
        $file = $this->root.'/app/Shared/Infrastructure/Database/DatabaseSchema.php';
        $contents = $this->read($file);
        $schemas = [];

        preg_match_all("/public const ([A-Z0-9_]+) = '([^']+)';/", $contents, $matches, PREG_SET_ORDER);

        foreach ($matches as $match) {
            $schemas[$match[1]] = $match[2];
        }

        ksort($schemas);

        return $schemas;
    }

    private function schemaForTable(string $table): string
    {
        if (str_starts_with($table, 'unresolved:')) {
            return 'unresolved';
        }

        if (! str_contains($table, '.')) {
            return 'public_or_vendor';
        }

        return explode('.', $table)[0];
    }

    private function ownerForSchema(string $schema): string
    {
        return match ($schema) {
            'core_audit' => 'audit',
            'core_authorization' => 'authorization',
            'core_exports' => 'exports',
            'core_files' => 'files',
            'core_identity' => 'identity',
            'core_notifications' => 'notifications',
            'core_privacy' => 'privacy',
            'core_settings' => 'settings',
            'core_teams' => 'teams',
            'optional_feature_flags' => 'feature_flags',
            'optional_imports' => 'imports',
            'optional_integrations' => 'integrations',
            'optional_managed_processes' => 'managed_processes',
            'optional_time_tracking' => 'time_tracking',
            'shared' => 'shared',
            default => $schema,
        };
    }

    private function firstStringArgument(string $arguments): ?string
    {
        if (preg_match('/[\'"]([^\'"]+)[\'"]/', $arguments, $match) !== 1) {
            return null;
        }

        return $match[1];
    }

    private function implicitColumnForBlueprintMethod(string $method): string
    {
        return match ($method) {
            'id' => 'id',
            'timestamps' => 'created_at,updated_at',
            'softDeletes' => 'deleted_at',
            'rememberToken' => 'remember_token',
            default => 'unresolved',
        };
    }

    private function compactExpression(string $expression): string
    {
        return trim(preg_replace('/\s+/', ' ', $expression) ?? $expression);
    }

    private function camelToSnake(string $value): string
    {
        $snake = preg_replace('/(?<!^)[A-Z]/', '_$0', $value) ?? $value;

        return strtolower($snake);
    }

    /**
     * @return list<array{file: string, line: int, match: string}>
     */
    private function mailSignals(): array
    {
        return $this->matchesInFiles(
            [
                ...$this->files('app', 'php'),
                ...$this->files('resources', 'php'),
                ...$this->files('database', 'php'),
            ],
            '/Mail::raw|toMail\s*\(|extends\s+Mailable|new\s+MailMessage|->subject\s*\(|->line\s*\(|->greeting\s*\(|->salutation\s*\(/',
        );
    }

    /**
     * @return list<array{file: string, line: int, match: string}>
     */
    private function seederSignals(): array
    {
        return $this->matchesInFiles(
            $this->files('database/seeders', 'php'),
            '/forceFill|DB::table|->insert\s*\(|->insertGetId\s*\(|->updateOrInsert\s*\(|Model::unguard|withoutEvents|Hash::make|assignRole|syncRoles|team_user|manager/',
        );
    }

    /**
     * @return list<array{file: string, line: int, match: string}>
     */
    private function runtimeSignals(): array
    {
        return $this->matchesInFiles(
            [
                ...$this->files('config', 'php'),
                ...$this->files('docker'),
                ...$this->files('.devcontainer'),
                ...$this->files('tools', 'sh', 'php', 'mjs'),
                ...$this->existingFiles([
                    '.dockerignore',
                    '.env.example',
                    'composer.json',
                    'package.json',
                    'playwright.config.ts',
                    'pnpm-lock.yaml',
                ]),
            ],
            '/DB_SEARCH_PATH|clamav|Horizon|queue:listen|queue:work|pnpm@latest|pnpm@|POSTGRES|PGDATA|chromium|playwright/i',
        );
    }

    /**
     * @return list<array{area: string, evidence: string, file: string, line: int, target: string}>
     */
    private function runtimeMatrixSignals(): array
    {
        $patterns = [
            ['area' => 'package_manager', 'pattern' => '/pnpm@latest|packageManager.*pnpm@/', 'target' => 'P28-RUNTIME-001/P28-RUNTIME-010'],
            ['area' => 'queue_worker', 'pattern' => '/queue:listen|queue:work|retry_after|timeout.*43200|--timeout=43200|--timeout=60/', 'target' => 'P28-RUNTIME-005'],
            ['area' => 'horizon', 'pattern' => '/Horizon|horizon|supervisor-1|maxProcesses|timeout.*43200/', 'target' => 'P28-RUNTIME-005'],
            ['area' => 'scheduler', 'pattern' => '/schedule:work|scheduler|SCHEDULER_HEARTBEAT/i', 'target' => 'P28-RUNTIME-006/P28-RUNTIME-007'],
            ['area' => 'database', 'pattern' => '/postgres:18|POSTGRES|PGDATA|DB_SEARCH_PATH|search_path/', 'target' => 'P28-RUNTIME-003/P28-RUNTIME-011'],
            ['area' => 'redis', 'pattern' => '/redis:8|REDIS_|redis-server|appendonly/', 'target' => 'P28-RUNTIME-003/P28-RUNTIME-005'],
            ['area' => 'search', 'pattern' => '/meilisearch|MEILI|SCOUT_DRIVER/', 'target' => 'P28-MOD-003/P28-RUNTIME-007'],
            ['area' => 'clamav', 'pattern' => '/clamav|ATLAS_FILES_SCANNER/i', 'target' => 'P28-RUNTIME-008'],
            ['area' => 'chromium_pdf', 'pattern' => '/chromium|playwright|PLAYWRIGHT_/', 'target' => 'P28-RUNTIME-009'],
            ['area' => 'network', 'pattern' => '/443:443|80:80|internal: true|network_mode: service:app/', 'target' => 'P28-RUNTIME-002'],
            ['area' => 'storage_backup', 'pattern' => '/app-storage|backup-data|backups|PGPASSWORD_FILE|backup/', 'target' => 'P28-RUNTIME-012'],
            ['area' => 'secrets', 'pattern' => '/_FILE\b|secrets:|secrets\/|password.txt|master_key/', 'target' => 'P28-RUNTIME-004'],
        ];

        $files = [
            ...$this->files('config', 'php'),
            ...$this->files('docker'),
            ...$this->files('.devcontainer'),
            ...$this->existingFiles([
                '.env.example',
                'composer.json',
                'package.json',
                'playwright.config.ts',
            ]),
        ];

        $signals = [];

        foreach ($files as $file) {
            $lines = explode("\n", $this->read($this->root.'/'.$file));

            foreach ($lines as $index => $line) {
                foreach ($patterns as $definition) {
                    if (preg_match($definition['pattern'], $line) !== 1) {
                        continue;
                    }

                    $signals[] = [
                        'area' => $definition['area'],
                        'evidence' => trim($line),
                        'file' => $file,
                        'line' => $index + 1,
                        'target' => $definition['target'],
                    ];
                }
            }
        }

        usort($signals, static function (array $left, array $right): int {
            return [$left['area'], $left['file'], $left['line'], $left['evidence']]
                <=> [$right['area'], $right['file'], $right['line'], $right['evidence']];
        });

        return $signals;
    }

    /**
     * @param  list<string>  $files
     * @return list<array{file: string, line: int, match: string}>
     */
    private function matchesInFiles(array $files, string $pattern): array
    {
        $matches = [];

        foreach ($files as $file) {
            $contents = $this->read($this->root.'/'.$file);
            $lines = explode("\n", $contents);

            foreach ($lines as $index => $line) {
                if (preg_match($pattern, $line, $match) !== 1) {
                    continue;
                }

                $matches[] = [
                    'file' => $file,
                    'line' => $index + 1,
                    'match' => $match[1] ?? trim($match[0]),
                ];
            }
        }

        return $matches;
    }

    /**
     * @param  list<string>  $roots
     * @return list<string>
     */
    private function matchingFiles(array $roots, string $pattern): array
    {
        $matches = [];

        foreach ($roots as $root) {
            foreach ($this->files($root) as $file) {
                if (preg_match($pattern, $file) === 1) {
                    $matches[] = $file;
                }
            }
        }

        sort($matches);

        return $matches;
    }

    private function firstFile(string $root, string $pattern): ?string
    {
        foreach ($this->files($this->relative($root), 'php') as $file) {
            if (preg_match($pattern, $file) === 1) {
                return $this->root.'/'.$file;
            }
        }

        return null;
    }

    /**
     * @param  list<string>  $files
     * @return list<string>
     */
    private function existingFiles(array $files): array
    {
        return array_values(array_filter(
            $files,
            fn (string $file): bool => is_file($this->root.'/'.$file),
        ));
    }

    private function matchString(string $contents, string $pattern): ?string
    {
        if (preg_match($pattern, $contents, $match) !== 1) {
            return null;
        }

        return $match[1];
    }

    /**
     * @return list<string>
     */
    private function files(string $root, string ...$extensions): array
    {
        $absoluteRoot = $this->root.'/'.$root;

        if (! file_exists($absoluteRoot)) {
            return [];
        }

        $files = [];
        $extensionMap = array_fill_keys($extensions, true);
        $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($absoluteRoot, FilesystemIterator::SKIP_DOTS));

        foreach ($iterator as $candidate) {
            if (! $candidate instanceof SplFileInfo || ! $candidate->isFile()) {
                continue;
            }

            $path = $candidate->getPathname();

            if (str_contains($path, '/vendor/') || str_contains($path, '/node_modules/') || str_contains($path, '/.git/')) {
                continue;
            }

            if ($extensionMap !== []) {
                $extension = $candidate->getExtension();
                $basename = $candidate->getBasename();

                if (! isset($extensionMap[$extension]) && ! isset($extensionMap[$basename])) {
                    continue;
                }
            }

            $files[] = $this->relative($path);
        }

        sort($files);

        return $files;
    }

    private function read(string $path): string
    {
        $contents = file_get_contents($path);

        if (! is_string($contents)) {
            throw new RuntimeException(sprintf('Unable to read [%s].', $path));
        }

        return $contents;
    }

    private function relative(string $path): string
    {
        return ltrim(str_replace($this->root, '', $path), '/');
    }

    private function listCell(mixed $items): string
    {
        if (! is_array($items) || $items === []) {
            return 'none';
        }

        return implode(', ', array_map(fn (mixed $item): string => $this->markdownInlineCode((string) $item), $items));
    }

    private function markdownInlineCode(string $value): string
    {
        return '`'.$this->markdownCodeText($value).'`';
    }

    private function markdownCodeText(string $value): string
    {
        return str_replace(['`', '|'], ["'", '\\|'], $value);
    }

    private function stringValue(mixed $value): string
    {
        return is_scalar($value) ? (string) $value : '';
    }
}

$root = dirname(__DIR__, 2);
$generator = new Phase28InventoryGenerator($root);
$mode = $argv[1] ?? '--json';

try {
    echo match ($mode) {
        '--json' => $generator->json(),
        '--markdown' => $generator->markdown(),
        '--framework-routes-markdown' => $generator->frameworkRoutesMarkdown(),
        '--persistence-markdown' => $generator->persistenceMarkdown(),
        '--runtime-markdown' => $generator->runtimeMarkdown(),
        '--backend-surfaces-markdown' => $generator->backendSurfacesMarkdown(),
        '--audit-markdown' => $generator->auditMarkdown(),
        '--prep-report-markdown' => $generator->prepReportMarkdown(),
        '--frontend-consistency-markdown' => $generator->frontendConsistencyMarkdown(),
        default => throw new InvalidArgumentException('Usage: php tools/phase28/generate-inventory.php [--json|--markdown|--framework-routes-markdown|--persistence-markdown|--runtime-markdown|--backend-surfaces-markdown|--audit-markdown|--prep-report-markdown|--frontend-consistency-markdown]'),
    };
} catch (Throwable $exception) {
    fwrite(STDERR, $exception->getMessage().PHP_EOL);
    exit(1);
}
