export const supportedLocales = ['pl', 'en'] as const;

export type SupportedLocale = (typeof supportedLocales)[number];

export const defaultLocale: SupportedLocale = 'pl';

export const translations = {
    pl: {
        'actions.change_language': 'Zmień język',
        'actions.close_navigation': 'Zamknij nawigację',
        'actions.collapse_sidebar': 'Zwiń panel boczny',
        'actions.expand_sidebar': 'Rozwiń panel boczny',
        'actions.logout': 'Wyloguj',
        'actions.open_navigation': 'Otwórz nawigację',
        'actions.switch_dark_theme': 'Włącz ciemny motyw',
        'actions.switch_light_theme': 'Włącz jasny motyw',
        'app.locale': 'Język',
        'app.version': 'Wersja',
        'auth.login.email': 'Email',
        'auth.login.head_title': 'Logowanie',
        'auth.login.password': 'Hasło',
        'auth.login.remember': 'Zapamiętaj mnie',
        'auth.login.session_conflict.cancel': 'Anuluj logowanie',
        'auth.login.session_conflict.continue': 'Kontynuuj tutaj',
        'auth.login.session_conflict.description':
            'Możesz przerwać logowanie albo kontynuować na tym urządzeniu. Kontynuacja zakończy poprzednią aktywną sesję.',
        'auth.login.session_conflict.title': 'Konto jest aktywne na innym urządzeniu',
        'auth.login.submit': 'Zaloguj',
        'auth.login.submitting': 'Logowanie...',
        'auth.login.subtitle': 'Uzyskaj dostęp do swojego obszaru pracy, aktywnego zespołu oraz narzędzi operacyjnych Atlas.',
        'auth.login.title': 'Zaloguj się',
        'auth.confirm_password.head_title': 'Potwierdź hasło',
        'auth.confirm_password.admin.subtitle': 'Podaj hasło ponownie, aby wejść do panelu administratora.',
        'auth.confirm_password.admin.title': 'Potwierdź dostęp administratora',
        'auth.confirm_password.high_risk.subtitle': 'Potwierdź hasło ponownie przed wykonaniem operacji wysokiego ryzyka.',
        'auth.confirm_password.high_risk.title': 'Potwierdź operację wysokiego ryzyka',
        'auth.confirm_password.mfa_code': 'Kod MFA',
        'auth.confirm_password.password': 'Hasło',
        'auth.confirm_password.submit': 'Potwierdź',
        'auth.confirm_password.submitting': 'Sprawdzanie...',
        'auth.confirm_password.subtitle': 'Podaj hasło ponownie, aby kontynuować.',
        'auth.confirm_password.title': 'Potwierdź hasło',
        'auth.reset_password.email': 'Email',
        'auth.reset_password.head_title': 'Ustaw hasło',
        'auth.reset_password.password': 'Nowe hasło',
        'auth.reset_password.password_confirmation': 'Powtórz nowe hasło',
        'auth.reset_password.submit': 'Ustaw hasło',
        'auth.reset_password.submitting': 'Zapisywanie...',
        'auth.reset_password.subtitle':
            'Ustaw własne hasło do konta Atlas. Ten formularz obsługuje także jednorazowe linki pierwszego logowania.',
        'auth.reset_password.title': 'Ustaw hasło',
        'auth.shell.body':
            'Bezpieczne centrum pracy dla zespołów obsługujących sprawy, działania terenowe, komunikację i nadzór nad procesami windykacyjnymi.',
        'auth.shell.heading': 'Operacyjny pulpit windykacji',
        'brand.subtitle': 'System Windykacyjny',
        'errors.403.description':
            'Nie masz skutecznego uprawnienia w aktywnym zespole albo aktywny zespół nie został wybrany. Poproś administratora o sprawdzenie dostępu.',
        'errors.403.title': 'Brak dostępu',
        'errors.404.description': 'Nie znaleźliśmy strony lub zasobu, którego szukasz.',
        'errors.404.title': 'Nie znaleziono strony',
        'errors.419.description': 'Sesja wygasła. Odśwież stronę i spróbuj ponownie.',
        'errors.419.title': 'Sesja wygasła',
        'errors.actions.back': 'Wróć',
        'errors.actions.home': 'Przejdź do pulpitu',
        'errors.default.description': 'Wystąpił problem po stronie systemu. Spróbuj ponownie za chwilę.',
        'errors.default.title': 'Coś poszło nie tak',
        'form.autocomplete.no_results': 'Brak wyników',
        'composable_view.empty': 'Brak danych.',
        'composable_view.loading': 'Ładowanie...',
        'composable_view.permission_required': 'Wymagane uprawnienie.',
        'composable_view.unavailable': 'Element niedostępny.',
        'form.autocomplete.placeholder': 'Szukaj',
        'form.entity_search.placeholder': 'Szukaj obiektu',
        'form.file.none': 'Nie wybrano pliku',
        'navigation.admin': 'Admin',
        'navigation.admin_dashboard': 'Pulpit administratora',
        'navigation.admin_panel': 'Panel administratora',
        'navigation.app_dashboard': 'Pulpit aplikacji',
        'navigation.aria.breadcrumb': 'Breadcrumb',
        'navigation.aria.main': 'Główna nawigacja',
        'navigation.aria.mobile': 'Mobilna nawigacja',
        'navigation.audit': 'Audyt',
        'navigation.dashboard': 'Pulpit',
        'navigation.group.identity_access': 'Tożsamość i dostęp',
        'navigation.group.organization': 'Organizacja',
        'navigation.group.oversight': 'Nadzór',
        'navigation.group.workspace': 'Praca',
        'navigation.logs': 'Logi',
        'navigation.managers': 'Managerowie',
        'navigation.modules': 'Moduły',
        'navigation.notifications': 'Powiadomienia',
        'navigation.packages': 'Presety',
        'navigation.permissions': 'Uprawnienia',
        'navigation.pulse': 'Pulse',
        'navigation.telescope': 'Telescope',
        'navigation.queues': 'Kolejki',
        'navigation.files': 'Pliki',
        'navigation.integrations': 'Integracje',
        'navigation.managed_processes': 'Procesy',
        'navigation.imports': 'Importy',
        'navigation.rate_limits': 'Limity żądań',
        'navigation.roles': 'Role',
        'navigation.schedules': 'Harmonogramy',
        'navigation.security_history': 'Historia bezpieczeństwa',
        'navigation.search': 'Wyszukiwanie',
        'navigation.teams': 'Zespoły',
        'navigation.users': 'Użytkownicy',
        'datatable.actions': 'Akcje',
        'datatable.boolean.no': 'Nie',
        'datatable.boolean.yes': 'Tak',
        'datatable.bulk.actions': 'Akcje masowe',
        'datatable.bulk.large.cancel': 'Anuluj',
        'datatable.bulk.large.confirm': 'Uruchom akcję',
        'datatable.bulk.large.description':
            'Zaznaczono ponad 5000 wierszy. Akcja masowa może potrwać dłużej i powinna być wykonana świadomie.',
        'datatable.bulk.large.title': 'Duża akcja masowa',
        'datatable.bulk.no_selection': 'Zaznacz wiersze, aby uruchomić akcję masową.',
        'datatable.bulk.processing.description': 'Przetwarzamy zaznaczone rekordy. Nie zamykaj tej karty do zakończenia operacji.',
        'datatable.bulk.processing.title': 'Trwa akcja masowa',
        'datatable.columns': 'Kolumny',
        'datatable.action.confirm.cancel': 'Anuluj',
        'datatable.action.confirm.confirm': 'Uruchom akcję',
        'datatable.action.confirm.description': '{subject}',
        'datatable.action.confirm.title': 'Potwierdź akcję',
        'datatable.empty': 'Brak rekordów.',
        'datatable.export': 'Eksport',
        'datatable.export.large.cancel': 'Anuluj',
        'datatable.export.large.confirm': 'Eksportuj',
        'datatable.export.large.description':
            'Eksportujesz ponad 5000 wierszy. Operacja może potrwać dłużej i chwilowo obciążyć przeglądarkę.',
        'datatable.export.large.title': 'Duży eksport',
        'datatable.export.processing.description': 'Przygotowujemy plik w przeglądarce. Przy dużych tabelach może to chwilę potrwać.',
        'datatable.export.processing.title': 'Przygotowywanie eksportu',
        'datatable.loading': 'Ładowanie...',
        'datatable.next': 'Następna',
        'datatable.no_results': 'Brak wyników dla bieżącego wyszukiwania.',
        'datatable.page': 'Strona',
        'datatable.page_of': 'Strona {page} z {pages}',
        'datatable.previous': 'Poprzednia',
        'datatable.rows_per_page': 'Wierszy na stronę',
        'datatable.rows': '{count} wierszy',
        'datatable.search': 'Szukaj',
        'datatable.select_all_filtered': 'Zaznacz wszystkie przefiltrowane',
        'datatable.select_row': 'Zaznacz wiersz',
        'datatable.select_visible_rows': 'Zaznacz widoczne wiersze',
        'datatable.selection.clear': 'Wyczyść zaznaczenie',
        'datatable.selection.count': 'Zaznaczono {count}',
        'datatable.status.active': 'Aktywne',
        'datatable.status.blocked': 'Zablokowane',
        'datatable.status.danger': 'Niebezpieczeństwo',
        'datatable.status.disabled': 'Wyłączone',
        'datatable.status.enabled': 'Włączone',
        'datatable.status.error': 'Błąd',
        'datatable.status.failed': 'Niepowodzenie',
        'datatable.status.info': 'Informacja',
        'datatable.status.inactive': 'Nieaktywne',
        'datatable.status.ok': 'OK',
        'datatable.status.pending': 'Oczekujące',
        'datatable.status.resolved': 'Rozwiązane',
        'datatable.status.running': 'W toku',
        'datatable.status.success': 'Sukces',
        'datatable.status.warning': 'Ostrzeżenie',
        'datatable.views': 'Widoki',
        'datatable.views.copy': 'Kopiuj',
        'datatable.views.copy_name': 'Kopia: {name}',
        'datatable.views.current': 'Bieżąca tabela',
        'datatable.views.default': 'Domyślny',
        'datatable.views.default_suffix': 'domyślny',
        'datatable.views.delete': 'Usuń',
        'datatable.views.name': 'Nazwa widoku',
        'datatable.views.name_placeholder': 'Nazwa widoku',
        'datatable.views.private': 'Prywatny',
        'datatable.views.save': 'Zapisz',
        'datatable.views.team': 'Współdzielony z zespołem',
        'datatable.views.type': 'Typ widoku',
        'datatable.views.update': 'Aktualizuj',
        'modal.cancel': 'Anuluj',
        'modal.affected_count': 'Liczba rekordów',
        'modal.irreversible': 'Tej operacji nie można cofnąć.',
        'modal.subject': 'Obiekt',
        'modal.typed_confirmation_label': 'Wpisz „{value}”, aby potwierdzić',
        'modal.failed_job_retry.title': 'Ponów failed job',
        'modal.failed_job_retry.description': 'Wybrany failed job zostanie ponownie dodany do kolejki.',
        'modal.failed_job_retry.confirm': 'Ponów job',
        'modal.failed_jobs_retry.title': 'Ponów failed jobs',
        'modal.failed_jobs_retry.description': 'Wybrane failed jobs zostaną ponownie dodane do kolejki. Wpisz wymagane potwierdzenie.',
        'modal.failed_jobs_retry.confirm': 'Ponów jobs',
        'modal.files_rescan.title': 'Ponownie przeskanować plik?',
        'modal.files_rescan.description': 'Plik pozostanie zablokowany do czasu zakończenia skanowania.',
        'modal.files_rescan.confirm': 'Skanuj ponownie',
        'toast.close': 'Zamknij komunikat',
        'toast.export.ready': 'Eksport gotowy',
        'pages.admin.packages.create.head_title': 'Utwórz preset',
        'pages.admin.packages.create.title': 'Utwórz preset',
        'pages.admin.packages.edit.head_title': 'Edytuj preset',
        'pages.admin.packages.edit.title': 'Edytuj preset',
        'pages.admin.packages.head_title': 'Presety',
        'pages.admin.packages.title': 'Presety',
        'pages.admin.permissions.head_title': 'Uprawnienia',
        'pages.admin.permissions.title': 'Uprawnienia',
        'pages.admin.logs.head_title': 'Logi aplikacji',
        'pages.admin.logs.title': 'Logi aplikacji',
        'pages.admin.queues.head_title': 'Kolejki',
        'pages.admin.queues.title': 'Kolejki',
        'pages.admin.files.head_title': 'Pliki',
        'pages.admin.files.title': 'Pliki',
        'pages.admin.integrations.head_title': 'Integracje',
        'pages.admin.integrations.title': 'Integracje',
        'pages.admin.managed_processes.head_title': 'Procesy',
        'pages.admin.managed_processes.title': 'Procesy',
        'pages.admin.imports.head_title': 'Importy',
        'pages.admin.imports.title': 'Importy',
        'pages.admin.rate_limits.head_title': 'Limity żądań',
        'pages.admin.rate_limits.title': 'Limity żądań',
        'pages.admin.roles.create.head_title': 'Utwórz rolę',
        'pages.admin.roles.create.title': 'Utwórz rolę',
        'pages.admin.roles.edit.head_title': 'Edytuj rolę',
        'pages.admin.roles.edit.title': 'Edytuj rolę',
        'pages.admin.roles.head_title': 'Role',
        'pages.admin.roles.title': 'Role',
        'pages.admin.teams.create.head_title': 'Utwórz zespół',
        'pages.admin.teams.create.title': 'Utwórz zespół',
        'pages.admin.teams.edit.head_title': 'Edytuj zespół',
        'pages.admin.teams.edit.title': 'Edytuj zespół',
        'pages.admin.teams.head_title': 'Zespoły',
        'pages.admin.teams.title': 'Zespoły',
        'pages.admin.managers.head_title': 'Managerowie',
        'pages.admin.managers.title': 'Managerowie',
        'pages.admin.users.create.head_title': 'Utwórz użytkownika',
        'pages.admin.users.create.title': 'Utwórz użytkownika',
        'pages.admin.users.edit.head_title': 'Edytuj użytkownika',
        'pages.admin.users.edit.title': 'Edytuj użytkownika',
        'pages.admin.users.index.head_title': 'Użytkownicy',
        'pages.admin.users.index.title': 'Użytkownicy',
        'pages.admin.audit.title': 'Audyt',
        'pages.dashboard.head_title': 'Pulpit',
        'pages.dashboard.title': 'Pulpit',
        'pages.security_history.empty': 'Nie ma jeszcze zdarzeń bezpieczeństwa.',
        'pages.security_history.head_title': 'Historia bezpieczeństwa',
        'pages.security_history.table.action': 'Akcja',
        'pages.security_history.table.impersonation_session': 'Sesja impersonacji',
        'pages.security_history.table.occurred_at': 'Wystąpiło',
        'pages.security_history.table.reason': 'Powód',
        'pages.security_history.table.result': 'Wynik',
        'pages.security_history.table.source': 'Źródło',
        'pages.security_history.table.team': 'Zespół',
        'pages.security_history.title': 'Historia bezpieczeństwa',
        'pages.notifications.head_title': 'Powiadomienia',
        'pages.notifications.title': 'Powiadomienia',
        'notifications.dropdown.empty': 'Brak powiadomień.',
        'notifications.dropdown.latest': 'Ostatnie powiadomienia',
        'notifications.dropdown.open_all': 'Pokaż wszystkie',
        'notifications.bulk.mark_read': 'Oznacz jako przeczytane',
        'notifications.open': 'Otwórz',
        'notifications.mark_read': 'Oznacz jako przeczytane',
        'notifications.table.body': 'Treść',
        'notifications.table.created_at': 'Utworzono',
        'notifications.table.deep_link': 'Link',
        'notifications.table.public_id': 'Public ID',
        'notifications.table.read': 'Przeczytane',
        'notifications.table.read_at': 'Przeczytano',
        'notifications.table.severity': 'Ważność',
        'notifications.table.team': 'Zespół',
        'notifications.table.title': 'Tytuł',
        'notifications.table.type': 'Typ',
        'notifications.unread_count': 'Nieprzeczytane: {count}',
        'team.active': 'Aktywny zespół',
        'team.select.continue': 'Kontynuuj',
        'team.select.description': 'Uprawnienia, nawigacja i dane obszaru pracy będą używać tego kontekstu zespołu.',
        'team.select.field': 'Zespół',
        'team.select.head_title': 'Wybierz zespół',
        'team.select.heading': 'Wybierz aktywny zespół',
        'team.select.title': 'Wybierz zespół',
        'user.default_name': 'Atlas User',
        'user.menu': 'Menu użytkownika',
    },
    en: {
        'actions.change_language': 'Change language',
        'actions.close_navigation': 'Close navigation',
        'actions.collapse_sidebar': 'Collapse sidebar',
        'actions.expand_sidebar': 'Expand sidebar',
        'actions.logout': 'Log out',
        'actions.open_navigation': 'Open navigation',
        'actions.switch_dark_theme': 'Enable dark theme',
        'actions.switch_light_theme': 'Enable light theme',
        'app.locale': 'Language',
        'app.version': 'Version',
        'auth.login.email': 'Email',
        'auth.login.head_title': 'Login',
        'auth.login.password': 'Password',
        'auth.login.remember': 'Remember me',
        'auth.login.session_conflict.cancel': 'Cancel login',
        'auth.login.session_conflict.continue': 'Continue here',
        'auth.login.session_conflict.description':
            'You can cancel this login or continue on this device. Continuing terminates the previous active session.',
        'auth.login.session_conflict.title': 'Account is active on another device',
        'auth.login.submit': 'Log in',
        'auth.login.submitting': 'Logging in...',
        'auth.login.subtitle': 'Access your workspace, active team, and Atlas operational tools.',
        'auth.login.title': 'Log in',
        'auth.confirm_password.head_title': 'Confirm password',
        'auth.confirm_password.admin.subtitle': 'Enter your password again to enter the admin panel.',
        'auth.confirm_password.admin.title': 'Confirm administrator access',
        'auth.confirm_password.high_risk.subtitle': 'Confirm your password again before continuing with a high-risk operation.',
        'auth.confirm_password.high_risk.title': 'Confirm high-risk operation',
        'auth.confirm_password.mfa_code': 'MFA code',
        'auth.confirm_password.password': 'Password',
        'auth.confirm_password.submit': 'Confirm',
        'auth.confirm_password.submitting': 'Checking...',
        'auth.confirm_password.subtitle': 'Enter your password again to continue.',
        'auth.confirm_password.title': 'Confirm password',
        'auth.reset_password.email': 'Email',
        'auth.reset_password.head_title': 'Set password',
        'auth.reset_password.password': 'New password',
        'auth.reset_password.password_confirmation': 'Confirm new password',
        'auth.reset_password.submit': 'Set password',
        'auth.reset_password.submitting': 'Saving...',
        'auth.reset_password.subtitle': 'Set your Atlas account password. This form also handles one-time first-login links.',
        'auth.reset_password.title': 'Set password',
        'auth.shell.body':
            'A secure work center for teams handling cases, field activities, communication, and debt collection process oversight.',
        'auth.shell.heading': 'Debt collection operations desk',
        'brand.subtitle': 'Debt Collection System',
        'errors.403.description':
            'You do not have an effective permission in the active team, or no active team is selected. Ask an administrator to review your access.',
        'errors.403.title': 'Access denied',
        'errors.404.description': 'We could not find the page or resource you are looking for.',
        'errors.404.title': 'Page not found',
        'errors.419.description': 'Your session has expired. Refresh the page and try again.',
        'errors.419.title': 'Session expired',
        'errors.actions.back': 'Go back',
        'errors.actions.home': 'Go to dashboard',
        'errors.default.description': 'The system ran into a problem. Try again in a moment.',
        'errors.default.title': 'Something went wrong',
        'form.autocomplete.no_results': 'No results',
        'composable_view.empty': 'No data available.',
        'composable_view.loading': 'Loading...',
        'composable_view.permission_required': 'Permission required.',
        'composable_view.unavailable': 'Element unavailable.',
        'form.autocomplete.placeholder': 'Search',
        'form.entity_search.placeholder': 'Search entity',
        'form.file.none': 'No file selected',
        'navigation.admin': 'Admin',
        'navigation.admin_dashboard': 'Admin dashboard',
        'navigation.admin_panel': 'Admin panel',
        'navigation.app_dashboard': 'Application dashboard',
        'navigation.aria.breadcrumb': 'Breadcrumb',
        'navigation.aria.main': 'Main navigation',
        'navigation.aria.mobile': 'Mobile navigation',
        'navigation.audit': 'Audit',
        'navigation.dashboard': 'Dashboard',
        'navigation.group.identity_access': 'Identity & access',
        'navigation.group.organization': 'Organization',
        'navigation.group.oversight': 'Oversight',
        'navigation.group.workspace': 'Workspace',
        'navigation.logs': 'Logs',
        'navigation.managers': 'Managers',
        'navigation.modules': 'Modules',
        'navigation.notifications': 'Notifications',
        'navigation.packages': 'Presets',
        'navigation.permissions': 'Permissions',
        'navigation.pulse': 'Pulse',
        'navigation.telescope': 'Telescope',
        'navigation.queues': 'Queues',
        'navigation.files': 'Files',
        'navigation.integrations': 'Integrations',
        'navigation.managed_processes': 'Processes',
        'navigation.imports': 'Imports',
        'navigation.rate_limits': 'Rate limits',
        'navigation.roles': 'Roles',
        'navigation.schedules': 'Schedules',
        'navigation.security_history': 'Security history',
        'navigation.search': 'Search',
        'navigation.teams': 'Teams',
        'navigation.users': 'Users',
        'datatable.actions': 'Actions',
        'datatable.boolean.no': 'No',
        'datatable.boolean.yes': 'Yes',
        'datatable.bulk.actions': 'Bulk actions',
        'datatable.bulk.large.cancel': 'Cancel',
        'datatable.bulk.large.confirm': 'Run action',
        'datatable.bulk.large.description':
            'More than 5000 rows are selected. This bulk action may take longer and should be run deliberately.',
        'datatable.bulk.large.title': 'Large bulk action',
        'datatable.bulk.no_selection': 'Select rows to run a bulk action.',
        'datatable.bulk.processing.description': 'Selected records are being processed. Keep this tab open until the operation finishes.',
        'datatable.bulk.processing.title': 'Running bulk action',
        'datatable.columns': 'Columns',
        'datatable.action.confirm.cancel': 'Cancel',
        'datatable.action.confirm.confirm': 'Run action',
        'datatable.action.confirm.description': '{subject}',
        'datatable.action.confirm.title': 'Confirm action',
        'datatable.empty': 'No records found.',
        'datatable.export': 'Export',
        'datatable.export.large.cancel': 'Cancel',
        'datatable.export.large.confirm': 'Export',
        'datatable.export.large.description':
            'You are exporting more than 5000 rows. This may take longer and can temporarily load the browser.',
        'datatable.export.large.title': 'Large export',
        'datatable.export.processing.description': 'Preparing the file in your browser. Large tables may take a moment.',
        'datatable.export.processing.title': 'Preparing export',
        'datatable.loading': 'Loading...',
        'datatable.next': 'Next',
        'datatable.no_results': 'No results match the current table search.',
        'datatable.page': 'Page',
        'datatable.page_of': 'Page {page} of {pages}',
        'datatable.previous': 'Previous',
        'datatable.rows_per_page': 'Rows per page',
        'datatable.rows': '{count} rows',
        'datatable.search': 'Search',
        'datatable.select_all_filtered': 'Select all filtered',
        'datatable.select_row': 'Select row',
        'datatable.select_visible_rows': 'Select visible rows',
        'datatable.selection.clear': 'Clear selection',
        'datatable.selection.count': '{count} selected',
        'datatable.status.active': 'Active',
        'datatable.status.blocked': 'Blocked',
        'datatable.status.danger': 'Danger',
        'datatable.status.disabled': 'Disabled',
        'datatable.status.enabled': 'Enabled',
        'datatable.status.error': 'Error',
        'datatable.status.failed': 'Failed',
        'datatable.status.info': 'Info',
        'datatable.status.inactive': 'Inactive',
        'datatable.status.ok': 'OK',
        'datatable.status.pending': 'Pending',
        'datatable.status.resolved': 'Resolved',
        'datatable.status.running': 'Running',
        'datatable.status.success': 'Success',
        'datatable.status.warning': 'Warning',
        'datatable.views': 'Views',
        'datatable.views.copy': 'Copy',
        'datatable.views.copy_name': 'Copy of {name}',
        'datatable.views.current': 'Current table',
        'datatable.views.default': 'Default',
        'datatable.views.default_suffix': 'default',
        'datatable.views.delete': 'Delete',
        'datatable.views.name': 'Saved view name',
        'datatable.views.name_placeholder': 'View name',
        'datatable.views.private': 'Private',
        'datatable.views.save': 'Save',
        'datatable.views.team': 'Team shared',
        'datatable.views.type': 'Saved view type',
        'datatable.views.update': 'Update',
        'modal.cancel': 'Cancel',
        'modal.affected_count': 'Affected records',
        'modal.irreversible': 'This operation cannot be undone.',
        'modal.subject': 'Object',
        'modal.typed_confirmation_label': 'Type "{value}" to confirm',
        'modal.failed_job_retry.title': 'Retry failed job',
        'modal.failed_job_retry.description': 'The selected failed job will be pushed back onto its configured queue.',
        'modal.failed_job_retry.confirm': 'Retry job',
        'modal.failed_jobs_retry.title': 'Retry failed jobs',
        'modal.failed_jobs_retry.description':
            'The selected failed jobs will be pushed back onto their configured queues. Type the required confirmation.',
        'modal.failed_jobs_retry.confirm': 'Retry jobs',
        'modal.files_rescan.title': 'Rescan this file?',
        'modal.files_rescan.description': 'The file remains blocked until scanning finishes.',
        'modal.files_rescan.confirm': 'Rescan',
        'toast.close': 'Close message',
        'toast.export.ready': 'Export ready',
        'pages.admin.packages.create.head_title': 'Create preset',
        'pages.admin.packages.create.title': 'Create preset',
        'pages.admin.packages.edit.head_title': 'Edit preset',
        'pages.admin.packages.edit.title': 'Edit preset',
        'pages.admin.packages.head_title': 'Presets',
        'pages.admin.packages.title': 'Presets',
        'pages.admin.permissions.head_title': 'Permissions',
        'pages.admin.permissions.title': 'Permissions',
        'pages.admin.logs.head_title': 'Application logs',
        'pages.admin.logs.title': 'Application logs',
        'pages.admin.queues.head_title': 'Queues',
        'pages.admin.queues.title': 'Queues',
        'pages.admin.files.head_title': 'Files',
        'pages.admin.files.title': 'Files',
        'pages.admin.integrations.head_title': 'Integrations',
        'pages.admin.integrations.title': 'Integrations',
        'pages.admin.managed_processes.head_title': 'Managed processes',
        'pages.admin.managed_processes.title': 'Managed processes',
        'pages.admin.imports.head_title': 'Imports',
        'pages.admin.imports.title': 'Imports',
        'pages.admin.rate_limits.head_title': 'Rate limits',
        'pages.admin.rate_limits.title': 'Rate limits',
        'pages.admin.roles.create.head_title': 'Create role',
        'pages.admin.roles.create.title': 'Create role',
        'pages.admin.roles.edit.head_title': 'Edit role',
        'pages.admin.roles.edit.title': 'Edit role',
        'pages.admin.roles.head_title': 'Roles',
        'pages.admin.roles.title': 'Roles',
        'pages.admin.teams.create.head_title': 'Create team',
        'pages.admin.teams.create.title': 'Create team',
        'pages.admin.teams.edit.head_title': 'Edit team',
        'pages.admin.teams.edit.title': 'Edit team',
        'pages.admin.teams.head_title': 'Teams',
        'pages.admin.teams.title': 'Teams',
        'pages.admin.managers.head_title': 'Managers',
        'pages.admin.managers.title': 'Managers',
        'pages.admin.users.create.head_title': 'Create user',
        'pages.admin.users.create.title': 'Create user',
        'pages.admin.users.edit.head_title': 'Edit user',
        'pages.admin.users.edit.title': 'Edit user',
        'pages.admin.users.index.head_title': 'Users',
        'pages.admin.users.index.title': 'Users',
        'pages.admin.audit.title': 'Audit',
        'pages.dashboard.head_title': 'Dashboard',
        'pages.dashboard.title': 'Dashboard',
        'pages.security_history.empty': 'There are no security events yet.',
        'pages.security_history.head_title': 'Security history',
        'pages.security_history.table.action': 'Action',
        'pages.security_history.table.impersonation_session': 'Impersonation session',
        'pages.security_history.table.occurred_at': 'Occurred at',
        'pages.security_history.table.reason': 'Reason',
        'pages.security_history.table.result': 'Result',
        'pages.security_history.table.source': 'Source',
        'pages.security_history.table.team': 'Team',
        'pages.security_history.title': 'Security history',
        'pages.notifications.head_title': 'Notifications',
        'pages.notifications.title': 'Notifications',
        'notifications.dropdown.empty': 'No notifications.',
        'notifications.dropdown.latest': 'Latest notifications',
        'notifications.dropdown.open_all': 'View all',
        'notifications.bulk.mark_read': 'Mark as read',
        'notifications.open': 'Open',
        'notifications.mark_read': 'Mark as read',
        'notifications.table.body': 'Message',
        'notifications.table.created_at': 'Created at',
        'notifications.table.deep_link': 'Deep link',
        'notifications.table.public_id': 'Public ID',
        'notifications.table.read': 'Read',
        'notifications.table.read_at': 'Read at',
        'notifications.table.severity': 'Severity',
        'notifications.table.team': 'Team',
        'notifications.table.title': 'Title',
        'notifications.table.type': 'Type',
        'notifications.unread_count': 'Unread: {count}',
        'team.active': 'Active team',
        'team.select.continue': 'Continue',
        'team.select.description': 'Your permissions, navigation, and workspace data will use this team context.',
        'team.select.field': 'Team',
        'team.select.head_title': 'Select team',
        'team.select.heading': 'Choose active team',
        'team.select.title': 'Select team',
        'user.default_name': 'Atlas User',
        'user.menu': 'User menu',
    },
} as const;

export type TranslationKey = keyof (typeof translations)[typeof defaultLocale];

export function normalizeLocale(locale: string | undefined): SupportedLocale {
    return supportedLocales.includes(locale as SupportedLocale) ? (locale as SupportedLocale) : defaultLocale;
}
